### ISSUE TITLE
[Test Case Results] triclr

### ISSUE THREAD

**Issue by triclr** [rlguy/Blender-FLIP-Fluids-Beta#10]
Here are all the test cases I have completed.
Every simulation ran smoothly, though at only around 10-17% CPU and maximum of ~3% GPU load for each of them.

[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723815/test_case_cascading_water_feature200.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723816/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723817/test_case_lighthouse125.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723818/test_case_viscous_net100.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723819/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks triclr!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
