### ISSUE TITLE
[Test Case Results] jcobreros

### ISSUE THREAD

**Issue by jcobreros** [rlguy/Blender-FLIP-Fluids-Beta#100]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749294/test_case_cascading_water_feature100.zip)

Looking great so far. A couple of remarks: as another user has commented, its not using 100% of the CPUs and at least according to Windows 10 Task Manager, it's not using my GPU, but I'm not sure if I should trust that.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Higher resolution simulations should increase CPU usage, but less than 100% CPU usage is normal. Low GPU usage is also normal. Here are some explanations:

> Lower than 100% CPU usage is normal. This is because fluid simulation is very memory heavy problem and memory access is slow compared to how fast your CPU is. In the simulator, there are many threads accessing large amounts of memory at the same time. The CPU must wait for memory to be fetched from RAM/Cache and this is what commonly causes decreased CPU usage. Another reason is that some calculations in the simulator are not able to be multithreaded efficiently, so these sections of calculations create a bottleneck which lowers average CPU usage.

> Low GPU usage is normal. The simulator offloads some calculations to the GPU to boost performance. Many FLIP calculations aren't perfectly suited for GPU processing, so the full power of the GPU cannot be 100% utilized. Often the GPU usage is under 5%, but with this low percentage, the calculations can still run much faster on the GPU than CPU. For example, mesh data is generated on the GPU and in tests, when running on CPU, these calculations could be two to five times slower. The performance boost will depend on your hardware. In the full beta version, you can try disabling the GPU features in the 'FLIP Fluid Advanced' settings panel to test if the calculations run faster on your CPU.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
