### ISSUE TITLE
[Test Case Results] samuelm0109

### ISSUE THREAD

**Issue by samuelm0109** [rlguy/Blender-FLIP-Fluids-Beta#102]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749355/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks samuelm0109!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by samuelm0109** [comment]
Thanks! Excited to work with the program more.

Best,

Samuel A. Martin
MA Student | Department of Anthropology | 2018
University of Central Florida
