### ISSUE TITLE
[Test Case Results] Rikere

### ISSUE THREAD

**Issue by rikere** [rlguy/Blender-FLIP-Fluids-Beta#107]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749527/test_case_cascading_water_feature100.zip)

First test done, nothing crashed, so trying the 400 resolution.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by rikere** [comment]
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752144/test_case_cascading_water_feature400.zip)

Huge lag when scrubbing through the timeline after the simulation, but it didn't lag during the simulation when I scrubbed it at the 25% mark.

I wonder if you could somehow load chunks to approve performance at full resolution preview? I have an app I use to watch back rendered frame sequences, you can set it to cache-ahead, so it will build a dynamic frame buffer around the playhead. An animation might be 40gb as EXR's, but it only has to load 2-3gb ahead of time and dumps the rest once it's past.

Not sure if that's feasible in blender though, that might be a deeper architectural change.

Also, love the quality. I could not achieve this with the built in fluid system on 32gb of ram. I've done other simulations where it just ran out of system memory for less detail than this in a smaller scene.

**Comment by rlguy** [comment]
This was actually a feature in the past, but it did not test and work well. This kind of feature does not seem possible with Blender at the moment.

The main problem was that it required huge amounts of memory. The frame mesh may be 50MB on disk, but once loaded into Blender, it could require 500MB of RAM to store all of the additional internal data that Blender uses. This does not allow for very many frames to be cached. Another problem was that loading meshes into Blender is very slow and the cache system was not able to keep up with the playback.

I have also experimented custom OpenGL drawing as another method of preview, but it will require Blender to improve the way addons are allowed to draw in the viewport. This method bypasses constructing the mesh into a Blender object for display, and instead is drawn directly by the addon in the viewport. This could be very fast, but at the moment addons can only draw one triangle at a time which is very very slow and has to be done whenever the viewport is redrawn. If Blender begins allowing batched draw operations for addons, then all triangles could be cached and drawn all at once and this feature could become feasible.

**Comment by rikere** [comment]
From the sounds of it, Blender's internals need some work. My only thought for a workaround:

What if you rendered it externally and projected it into the viewport via compositing? So you have an external, super-fast renderer and some kinda toggle. You pass the current camera angle/settings from blender to an external GL renderer, and that returns a bitmap that will match up to the viewport, to composite over like a reference image/video?

It is a stupidly round-about way to do it that *probably* isn't worth persuing, but wanted to throw it out there if there is enough demand for the feature. I'm fine with the proxy-mesh.
