### ISSUE TITLE
[Test Case Results] Derjyn

### ISSUE THREAD

**Issue by Derjyn** [rlguy/Blender-FLIP-Fluids-Beta#108]
viscous_net test case ran without issue @ defaults, took 0:21:34
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749578/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran okay, but you are affected by issue #7. The simulator seems to be detecting your integrated graphics chip as more powerful than your GTX 750ti card. One reason for this could be a known issue with OpenCL misreporting NVidia hardware information. There will be a fix for this when functionality to set GPU compute device is added in the addon.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by Derjyn** [comment]
About issue #7 - yes, I left the setting to CPU default.  Would you like me to set that to GPU on the same test case blend, and submit the results here?

**Comment by rlguy** [comment]
No, that's okay, it would probably be best to wait until this issue is fixed until submitting more results.
