### ISSUE TITLE
[Test Case Results] guilliamPL

### ISSUE THREAD

**Issue by guilliamPL** [rlguy/Blender-FLIP-Fluids-Beta#109]
So far every simulation done without problems. Next days I will try higher resolutions. Good job.

[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749571/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749572/test_case_lighthouse125.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749573/test_case_viscous_net100.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749574/test_case_cascading_water_feature100.zip)

Best,
Chris

**Comment by rlguy** [comment]
Thanks guilliamPL!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
