### ISSUE TITLE
[Test Case Results] vmxeo

### ISSUE THREAD

**Issue by vmxeo** [rlguy/Blender-FLIP-Fluids-Beta#11]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723814/test_case_cascading_water_feature100.zip)

CPU usage was around ~30%, GPU usage was minimal.

**Comment by rlguy** [comment]
Thanks vmxeo!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
