### ISSUE TITLE
[Test Case Results] manhellis

### ISSUE THREAD

**Issue by manhellis** [rlguy/Blender-FLIP-Fluids-Beta#111]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749645/test_case_cascading_water_feature100.zip)
No issues here, except it seemed to pause once and awhile and I had to resume it. Also GPU utilization was little to none.

Looking forward to it!

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors aside from the simulation pausing on its own. Please let me know if this frequently continues to happen.

Overall low GPU usage is normal and increases with larger simulations.

> Low GPU usage is normal. The simulator offloads some calculations to the GPU to boost performance. Many FLIP calculations aren't perfectly suited for GPU processing, so the full power of the GPU cannot be 100% utilized. Often the GPU usage is under 5%, but with this low percentage, the calculations can still run much faster on the GPU than CPU. For example, mesh data is generated on the GPU and in tests, when running on CPU, these calculations could be two to five times slower. The performance boost will depend on your hardware. In the full beta version, you can try disabling the GPU features in the 'FLIP Fluid Advanced' settings panel to test if the calculations run faster on your CPU.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
