### ISSUE TITLE
[Test Case Results] qs2435

### ISSUE THREAD

**Issue by qs2435** [rlguy/Blender-FLIP-Fluids-Beta#115]
There was no issues/errors in my pc.
Though I noticed Blender only use about 35%-55% of CPU during the simulation, is that normal?

[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749923/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749924/test_case_viscous_net65.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749925/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749926/test_case_fluid_in_an_invisible_box100.zip)

**Comment by qs2435** [comment]
Also I noticed there is no significant GPU usage during the simulation

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

CPU/GPU usage is normal and generally will increase on higher resolution simulations. Here's a bit of an explanation:

> Lower than 100% CPU usage is normal. This is because fluid simulation is very memory heavy problem and memory access is slow compared to how fast your CPU is. In the simulator, there are many threads accessing large amounts of memory at the same time. The CPU must wait for memory to be fetched from RAM/Cache and this is what commonly causes decreased CPU usage. Another reason is that some calculations in the simulator are not able to be multithreaded efficiently, so these sections of calculations create a bottleneck which lowers average CPU usage.

> Low GPU usage is normal. The simulator offloads some calculations to the GPU to boost performance. Many FLIP calculations aren't perfectly suited for GPU processing, so the full power of the GPU cannot be 100% utilized. Often the GPU usage is under 5%, but with this low percentage, the calculations can still run much faster on the GPU than CPU. For example, mesh data is generated on the GPU and in tests, when running on CPU, these calculations could be two to five times slower. The performance boost will depend on your hardware. In the full beta version, you can try disabling the GPU features in the 'FLIP Fluid Advanced' settings panel to test if the calculations run faster on your CPU.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
