### ISSUE TITLE
[Test Case Results] TackyX

### ISSUE THREAD

**Issue by TackyX** [rlguy/Blender-FLIP-Fluids-Beta#117]
Heyo, I ran a couple of the test scenes and seemed to have no issues. Here are the results.
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1750165/test_case_lighthouse125.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1750166/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
