### ISSUE TITLE
[Unable to run test] Library pyfluid problem

### ISSUE THREAD

**Issue by hrisek** [rlguy/Blender-FLIP-Fluids-Beta#12]
I still get error in system console:
"Unable to load library: pyfluid".
I installed addon correctly.
And here is windows which is opened after i click "Run Test Case":
![blender_error](https://user-images.githubusercontent.com/36200323/36203870-65412618-1189-11e8-8b47-e763a3f5d314.jpg)

**Comment by hrisek** [comment]
I solved a problem by installing a new nvidia graphic drivers :)

**Comment by rlguy** [comment]
Great to hear that you were able to solve this issue!
