### ISSUE TITLE
[Test Case Results] avmd45

### ISSUE THREAD

**Issue by avmd45** [rlguy/Blender-FLIP-Fluids-Beta#120]
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1751288/test_case_viscous_net100.zip)
Viscous Net simulation. Worked.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
