### ISSUE TITLE
[Test Case Results] tuffkidblabla

### ISSUE THREAD

**Issue by tuffkidblabla** [rlguy/Blender-FLIP-Fluids-Beta#121]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1751319/test_case_fluid_in_an_invisible_box100.zip)
Everything ran smoothly! Looks good!

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by rlguy** [comment]
> tuffkidblabla:
> [test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1751761/test_case_viscous_net100.zip)
Everything went fine!

Thanks!
