### ISSUE TITLE
[Test Case Results] tuffkidblabla

### ISSUE THREAD

**Issue by tuffkidblabla** [rlguy/Blender-FLIP-Fluids-Beta#125]
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1751761/test_case_viscous_net100.zip)
Everything went fine!

**Comment by rlguy** [comment]
Thanks for the results! You may submit all of your results in the same issue thread. I have add this test to your original results thread here: #121
