### ISSUE TITLE
[Test Case Results] AlanAccenture

### ISSUE THREAD

**Issue by AlanAccenture** [rlguy/Blender-FLIP-Fluids-Beta#127]
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752131/test_case_lighthouse125.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752335/test_case_fluid_in_an_invisible_box200.zip)

**Comment by rlguy** [comment]
Hey AlanAccenture, you may post all of your test results in the same thread. I have added these results to your original issue here: #122
