### ISSUE TITLE
[Test Case Results] Joey-Wittmann

### ISSUE THREAD

**Issue by Joey-Wittmann** [rlguy/Blender-FLIP-Fluids-Beta#128]
[test_case_lighthouse250.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752183/test_case_lighthouse250.zip)
It worked!

**Comment by rlguy** [comment]
Thanks Joey-Wittmann!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
