### ISSUE TITLE
[Test Case Results] alex3dpl

### ISSUE THREAD

**Issue by alex3dpl** [rlguy/Blender-FLIP-Fluids-Beta#129]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752333/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by alex3dpl** [comment]
Hi,
my dropbox folder contains only readme file - it's not updated. Thanks for you work and for inviting me. I'm working on watermill project, so it will be good occasion for testing.

**Comment by rlguy** [comment]
Sorry about this! You are correct, I must have forgot to enable your builds. It should be updated now.

**Comment by alex3dpl** [comment]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1760114/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1760115/test_case_lighthouse125.zip)
