### ISSUE TITLE
[Test Case Results] GCharb

### ISSUE THREAD

**Issue by GCharb** [rlguy/Blender-FLIP-Fluids-Beta#13]
Here is a first test, it went okay at 100 resolution.

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723976/test_case_cascading_water_feature100.zip)

I am now simulating the highest resolution tests, but it might take a while before I can post them as they take a very long time to simulate, CPU load was low on the 100 resolution test, but it gets over 90% at time with the one i am running at the moment at 400 resolution, as it goes, it should take over 12 hours to simulate!

**Comment by rlguy** [comment]
Thanks GCharb!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by GCharb** [comment]
Thanks rlguy, found the add-on, will look into it as soon as the current test is done!

**Comment by GCharb** [comment]
Here is my latest test, took 11 hours to simulate, crashed twice, my log says it was a memory peak problem, it created nearly 54 million faces, which my system handles pretty well I must say, I rendered a few frames no problems!

[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725496/test_case_fluid_in_an_invisible_box400.zip)

**Comment by GCharb** [comment]
latest test, took over 30 hours to simulate, crashed a few times, CPU usage was pretty good, GPU usage was 10-15% according to my GPUZ log file.

[test_case_lighthouse500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732111/test_case_lighthouse500.zip)
