### ISSUE TITLE
 [Test Case Results] fineskimo

### ISSUE THREAD

**Issue by fineskimo** [rlguy/Blender-FLIP-Fluids-Beta#131]
Hi there, had no issues with any of the test cases I ran.

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752584/test_case_cascading_water_feature100.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752585/test_case_viscous_net65.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1752586/test_case_lighthouse125.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
