### ISSUE TITLE
[Feature Request] Obstacle Properties

### ISSUE THREAD

**Issue by HEEROCKSS** [rlguy/Blender-FLIP-Fluids-Beta#133]
Hey Ryan. 
While playing around with your awesome Addon, i came across some Situations where a nice Feature from another Flip Fluid Software came to my Mind. It has Obstacles that can be Solid or a Void Object. Solid Obstacles are the default one`s like the one we have, but Void objects can be penetrated by the Fluid and the Fluid/Particles will be deleted inside the Object.
This can be pretty handy in some cases!

For Example: If you have an Animation with some Fluid glitching through a Solid Wall (even at highres/high substeps) you can keep your Animation clean by adding a Void Object outside of that Wall. So in the Rendered Animation, no one will notice it.

**Comment by rlguy** [comment]
Hey, this sounds like what the [Outflow](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Outflow-Object-Settings) objects do. Is this correct, or am I misunderstanding something?

**Comment by HEEROCKSS** [comment]
Ah nevermind... Its exactly what i meant! Thank you

**Comment by rlguy** [comment]
No problem!
