### ISSUE TITLE
[Test Case Results] DVFXAustralia

### ISSUE THREAD

**Issue by DVFXAustralia** [rlguy/Blender-FLIP-Fluids-Beta#135]
Hey, I ran the lighthouse.blend test case at 250 resolution and it ran okay with no errors. Here are the results:

[test_case_lighthouse250.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1753468/test_case_lighthouse250.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by DVFXAustralia** [comment]
Hey, I ran the viscous_net.blend test case at 100 resolution and it ran okay with no errors. Here are the results:

[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1766140/test_case_viscous_net100.zip)


I ran the fluid_in_an_invisible_box.blend test case at 200 resolution and it ran okay with no errors. Here are the results:

[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1766143/test_case_fluid_in_an_invisible_box200.zip)


 I ran the cascading_water_feature200e.blend test case at 200 resolution and it ran okay with no errors. Here are the results:

[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1766145/test_case_cascading_water_feature200.zip)

**Comment by DVFXAustralia** [comment]
Hey, I ran all the four test cases, they ran smoothly with no problems:


[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1863650/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1863651/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1863653/test_case_lighthouse125.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1863654/test_case_viscous_net100.zip)



:
