### ISSUE TITLE
[Bug/Error] Unable to load library: pyfluid

### ISSUE THREAD

**Issue by joquist** [rlguy/Blender-FLIP-Fluids-Beta#136]
Attempting to run a test case throws up the following error. Windows error and Blender System console errors attached below. I installed the FLIP addon via User Preferences ( "Install Add-on from File" ), currently running Blender 2.79.

![flip_error](https://user-images.githubusercontent.com/1666190/36623077-a7a46a5e-18cf-11e8-804d-47005f3f0ea7.jpg)
[FLIP_console_error.txt](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1753643/FLIP_console_error.txt)

**Comment by rlguy** [comment]
Check this issue: #6. The common fix for this is to reinstall/update graphics drivers. Let me know if this solution doesn't work.
