### ISSUE TITLE
[Test Case Results] talliepie

### ISSUE THREAD

**Issue by talliepie** [rlguy/Blender-FLIP-Fluids-Beta#139]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1754190/test_case_cascading_water_feature100.zip)
[test_case_lighthouse375.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1754191/test_case_lighthouse375.zip)

Ran two test cases without issue, one a little longer to see how that went!

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
