### ISSUE TITLE
Nothing shown in the Flip Fluid panel.

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#14]
Hi, thank you for inviting me as a beta tester. 

I have installed the addon, bl_flip_fluids_test_suite-x64_v0.1.1t.zip, without any error message.
And I confirmed that the Flip fluid button in the Physics.
After clicking the button, only header come up. But there is no contents.

![iamge1](https://user-images.githubusercontent.com/36343687/36205004-91157b08-11d0-11e8-92d1-7fcd82359a4c.jpg)

![image2](https://user-images.githubusercontent.com/36343687/36205013-94a0be04-11d0-11e8-8d37-b0a6e4ff9176.jpg)

![iamge3](https://user-images.githubusercontent.com/36343687/36205016-972c325c-11d0-11e8-8b6e-77e6ef7bd17d.jpg)

The some error messages are caused by other addon, I think.

**Comment by rlguy** [comment]
Hey,

This is working as expected. The addon you were given is the **FLIP Fluids Test Suite** addon, which on runs on a set of test scenes. The addon won't work with other scenes. One you run a test case with the test suite addon, you will begin receiving full versions of the beta addon.

See [How to Run a Test Case](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/How-to-Run-a-Test-Case) for more info on how to use the test suite addon.
