### ISSUE TITLE
Transforms not working

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#145]
Hi,

Although in new beta it is now possible to translate/rotate a cache properly.

There are still issues creating a sim with a transformed domain (here I have made fluid a child of the domain)

![bug](https://user-images.githubusercontent.com/36420510/36632801-3fb4da46-1983-11e8-8b72-a5f47ebb6ff6.JPG)
[transformBug.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1754654/transformBug.zip)

**Comment by Mitsuma** [comment]
I had an issue with a random localized Fluid object but could resolve it by applying the size and location in Blender.
Ctrl+A by default

**Comment by qs2435** [comment]
I've this similar issues, as @Mitsuma said, apply the scale and location will fix it

**Comment by rlguy** [comment]
>I had an issue with a random localized Fluid object but could resolve it by applying the size and location in Blender.
Ctrl+A by default

This will have to remain the workaround for this. There is no Blender callback to detect when the user changes the origin of the domain, so the addon cannot correct the cache object transformations automatically. The way to resolve this will be to either apply transformations to the cache meshes, or to manually reset the transformation by deleting the cache mesh objects. The addon should regenerate them in the correct order.

I have added a note about this to the [Domain Object Settings](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Object-Settings) page:

> Try to avoid applying location/scale transformations to the domain (_CTRL+A_). Applying location and scale transformations may cause the cache meshes to be loaded at an incorrect scale or location in the scene. If your cache meshes are loading at an incorrect scale/location, you may correct this by applying transformations (_CTRL+A_) to the cache mesh objects. Alternatively, you may delete the cache mesh objects and they will regenerate correctly when the frame is reloaded.
