### ISSUE TITLE
[Test Case Results] clb92

### ISSUE THREAD

**Issue by clb92** [rlguy/Blender-FLIP-Fluids-Beta#149]
I notice that the file in the exported test case says "completed frames 0". I assume that's because I loaded the previously baked cache into the file after having closed Blender.

[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1755543/test_case_fluid_in_an_invisible_box400.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
