### ISSUE TITLE
[Test Case Results] szerhusenBC

### ISSUE THREAD

**Issue by szerhusenBC** [rlguy/Blender-FLIP-Fluids-Beta#15]
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724183/test_case_viscous_net100.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724184/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724185/test_case_cascading_water_feature200.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724186/test_case_fluid_in_an_invisible_box100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724187/test_case_fluid_in_an_invisible_box200.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724188/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724189/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks szerhusenBC!

I checked your results and it looks like the simulator ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
