### ISSUE TITLE
[Test Case Results] szczyglo74

### ISSUE THREAD

**Issue by szczyglo74** [rlguy/Blender-FLIP-Fluids-Beta#150]
Hey!
I ran tests scenes without problems. Here are results so far:

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756214/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756215/test_case_cascading_water_feature200.zip)
[test_case_cascading_water_feature300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756216/test_case_cascading_water_feature300.zip)
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756217/test_case_cascading_water_feature400.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756218/test_case_fluid_in_an_invisible_box100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756219/test_case_fluid_in_an_invisible_box200.zip)
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756220/test_case_fluid_in_an_invisible_box300.zip)
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756221/test_case_fluid_in_an_invisible_box400.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756222/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756223/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by szczyglo74** [comment]
That's it for tests scenes: 

[test_case_lighthouse250.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1777972/test_case_lighthouse250.zip)
[test_case_lighthouse375.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1777973/test_case_lighthouse375.zip)
[test_case_lighthouse500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1777974/test_case_lighthouse500.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1777975/test_case_viscous_net100.zip)
[test_case_viscous_net150.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1777976/test_case_viscous_net150.zip)
[test_case_viscous_net200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1777977/test_case_viscous_net200.zip)

Time to do something more creative than click "Run Test Case" :)
