### ISSUE TITLE
[Test Case Results] NunoFelix

### ISSUE THREAD

**Issue by NunoFelix** [rlguy/Blender-FLIP-Fluids-Beta#151]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756746/test_case_fluid_in_an_invisible_box100.zip)

Hi. 
This is my first test case. The sim looks great!
I don't know if this is normal, but only 10 to 15 percent of my CPU's is beeing used during calculations.

Thanks

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

This may explain CPU usage: https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
