### ISSUE TITLE
[Bug] Massive Difference in Final/Preview

### ISSUE THREAD

**Issue by rikere** [rlguy/Blender-FLIP-Fluids-Beta#155]
I have a scene with 2 resolutions: 400 final and 45 preview. On the 400 everything is perfect. On the 45 however, the fluid basically disappears entirely.

Preview Frame 1:
![image](https://user-images.githubusercontent.com/22123117/36680205-1b7d6916-1ae3-11e8-9233-ce6f4922402d.png)

Preview Anytime After Frame 1:
![image](https://user-images.githubusercontent.com/22123117/36680177-041d4796-1ae3-11e8-86cb-8ad3db4acf50.png)

Preview Frame 1:
![image](https://user-images.githubusercontent.com/22123117/36680205-1b7d6916-1ae3-11e8-9233-ce6f4922402d.png)

Final Frame 1:
![image](https://user-images.githubusercontent.com/22123117/36680256-3c982118-1ae3-11e8-9e02-bcca18dcbc79.png)

Final Anytime After Frame 1:
![image](https://user-images.githubusercontent.com/22123117/36680284-4f75d226-1ae3-11e8-8b38-809c858edc15.png)

The final works as expected, but the preview seems bugged. I can get the droplets higher up not working, but the puddle seems like it shouldn't just poof into nothingness.

**Comment by rlguy** [comment]
Hey rikere,

This is working as intended. The preview mesh is a very very rough approximation of the final mesh intended for quick viewing. Meshing works on a grid and at a resolution of 45, a lot of the fine detail in the final mesh (such as thin layers of fluid and small droplets) will be lost. If you want more detail in the preview, try raising the preview resolution to something like 100 or 150 before baking.

**Comment by rikere** [comment]
A small feature request then: It'd be helpful to have some kind of visual for how small the grid detail (voxel?) is. I'd figured since the water at the bottom survive frame 1, it would've stuck around.

**Comment by rlguy** [comment]
Good suggestion! There is a feature to display the simulation grid and mesh grid, but not yet the preview grid. I have added a feature request to display the preview grid here: #160
