### ISSUE TITLE
[Feature Request] Generating whitewater after the base FLIP simulation?

### ISSUE THREAD

**Issue by guilliamPL** [rlguy/Blender-FLIP-Fluids-Beta#157]
Hi,

Will it be possible to simulate whitewater based on previously simulated and cached FLIP simulation?
It can be a very handy option and save a lot of time.

Best,
Chris

**Comment by rlguy** [comment]
Hey guilliamPL,

I have thought about this before, but at the moment it doesn't seem like a reasonable feature to implement. This would require saving a lot of additional FLIP simulation data to disk. This could be 2GB+ per frame for larger simulations. 

The whitewater simulator also reuses a lot of calculations from the FLIP simulation. This would require recalculating a lot of data which could take quite a bit of additional time for each frame.

I'll be closing this issue, but I may reopen this feature request at a later date if I can find a feasible way to implement this.
