### ISSUE TITLE
[Improvement/Feature Request] Prevent mesh artifacts against curved surfaces

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids-Beta#158]
### Problem

Sometimes, the generated fluid surface will cause rendering artefacts against curves surfaces:

![meshing_artifacts_curves_surface](https://user-images.githubusercontent.com/4285191/36692764-d1bc6fe2-1aed-11e8-9923-9395ab569fff.jpg)

This is caused by gaps or intersections between the fluid surface and obstacle object. The cause of this problem is that the simulator tries to create a smooth mesh around curved obstacles, but sometimes the mesh grid is not detailed enough to create a perfect mesh and this is why these gaps/intersections happen.

### Solution

Add an option to the [FLIP Fluid Surface](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Surface-Settings) settings to disable smooth meshing around obstacle objects. When disabled, the mesher will not attempt to create a smooth interface between the fluid and obstacle object, but will instead be allowed fully intersect into the obstacle surface. This will eliminated these 'air gaps' that are causing rendering artifacts.

### Workarounds

Until this is implemented, here are some workarounds/fixes to this problem:

1. **Increase surface subdivision level** - This will generate a higher resolution mesh. The added level of detail should be enough to eliminated the artifacts. This will take more time to compute.
2. **Move/scale the object after simulation** - Moving the location of the object slightly so that the fluid surface fully intersects the object could hide the artifacts.

**Comment by alex3dpl** [comment]
Same here, thx explanation.

**Comment by rlguy** [comment]
An option to enable/disable meshing around obstacles has been added. Disable this option to prevent mesh artifacts. This will be included in the next addon beta version (**0.1.3b**).

![mesh_around_obstacles](https://user-images.githubusercontent.com/4285191/36878458-f3580b74-1d73-11e8-9e90-3cffe5bf540f.jpg)
