### ISSUE TITLE
[Test Case Results] left_coaster

### ISSUE THREAD

**Issue by left-coaster** [rlguy/Blender-FLIP-Fluids-Beta#16]
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724256/test_case_cascading_water_feature200.zip)

An error occurred when trying to export the test case data (see attached image) so I manually compressed and renamed the directory.  Hopefully everything is there.

Thanks,
Bruce

![errorimage](https://user-images.githubusercontent.com/36162461/36208354-cc1ecf84-1166-11e8-9a1b-e041a4206908.png)

**Comment by GCharb** [comment]
This was resolved yesterday, you only need to get the addon again, uninstall the old one and install the new one!

**Comment by rlguy** [comment]
This is correct, thanks GCharb!

Sorry for the inconvenience, left-coaster, this was a mistake on my part when launching the beta.
