### ISSUE TITLE
[Question] Preview Resolution

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids-Beta#163]
Quick question about the Preview Resolution setting and all the preview stuff in general.
Can you actually disable the preview resolution generation?
Probably better to ask first is if the preview takes extra time to generate.

I can see it takes up some extra space, wonder if it also takes up time in the baking process.
If so can you also disable the preview mesh generation?
I'm find myself being pretty stable and fast even with the final one showing so often I don't actually make use of the preview mesh. Saved space and possible time in baking would be appreciated.
I haven't tested if setting the preview res to 0 does anything or breaks anything.

**Comment by rlguy** [comment]
At the moment, preview meshes cannot be disabled. Later on I’m planning to add more customizability for what to export to cache. Such as disable preview, disable surface, enable particles, etc.

Generating preview meshes takes a very small amount of time compared to everything else. For now, if you don’t want them to take up space, I’d suggest setting their resolutions to 1.
