### ISSUE TITLE
[Question] Wind Effect?

### ISSUE THREAD

**Issue by guitartom47** [rlguy/Blender-FLIP-Fluids-Beta#164]
Is it possible to have wind effect how the simulation runs? Perhaps it would be nice with the fluid simulation - but certainly it would be great to have some sort of wind effect on the spray! 

Forgive me if this has been mentioned already.

**Comment by rlguy** [comment]
Not at the moment. It is planned to add support for Blender’s force types. This will probably be the next large feature added after release.

Never thought about the cool effects this feature would have on whitewater. Good point!
