### ISSUE TITLE
[Feature Request] Playback (offset) start frame

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#165]
Hi,

It makes sense to (often) start making sims at frame 0.

However, when you want to use the cache sometimes it is helpful to have them start at a different frame.

Therefore having a playback frame offset would be quite handy.

Thanks

**Comment by rlguy** [comment]
Good suggestion!

**Comment by dafassi** [comment]
Maybe this is possible using „hold frame“? Check if this is animatable...

**Comment by rlguy** [comment]
This actually does work! But is a more complex workaround than it should be for this feature. I'll just add a simple 'offset' parameter in the helper menu display settings.

**Comment by rlguy** [comment]
This has been added and will be included in the next beta version (**v0.1.3b**).

![playback_offset](https://user-images.githubusercontent.com/4285191/36873901-d84ccffa-1d5e-11e8-9c46-6295e13477f9.jpg)
