### ISSUE TITLE
Importing as a link doesn't appear to work

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#166]
Hi,

I might be doing something wrong (likely!).

However, when I import my fluid objects as link objects (or when I have added them all to the same group and link imported them) they don't do anything.

Thanks

**Comment by rlguy** [comment]
To import a simulation cache into a scene:
1. Create an object that will act as the domain
2. Set object FLIP type to domain
3. Set the domain cache directory to the simulation you want to import

Note: You will need to enable whitewater simulation to enable loading whitewater meshes.

Is this suitable for what you’re trying to do? I’m quite a beginner in regards to Blender features so I’m not entirely sure if linking gives different functionality than the above instructions.

**Comment by RevDr** [comment]
Hi,

Linking loads into Scene A and items (or group of items) from Scene B.

So if I change the object in scene B - the next time I load scene A that change is reflected.

I think your work around will work - thank you.  

Come to think of it - I think your method will make my case easier.  I'll reorganize my scene hierarchy around a little to accommodate your method and get back to you in a day or two to confirm.

**Comment by Mitsuma** [comment]
Think you can not just link a simulation.  
They are bound to the cache files and can only be loaded in a new scene.

At best you can link everything around the simulation but if you need the simulation in another scene you need to load it separately. Once loaded in both scene it should actually act like a link because you load the same cache.

**Comment by RevDr** [comment]
Just to confirm RLGuy - your workaround is good for me.
