### ISSUE TITLE
[Feature request] VDB export.

### ISSUE THREAD

**Issue by niklassjogren** [rlguy/Blender-FLIP-Fluids-Beta#168]
Any plans or thoughts on export to OpenVDB, if it's possible and if it should benefit the addon?
I really would like that option!
/Niklas

**Comment by rlguy** [comment]
OpenVDB support will likely not be added to this project. It adds quite a few code dependencies and complicates  building and distribution too much for a small feature. I have found that it is straightforward to build on Linux, but for Windows I had a lot of trouble.

If In the future Blender adds the required OpenVDB export functionality to the Python API, this feature request may be reopened.
