### ISSUE TITLE
[Test Case Results] AhmedSalih3d

### ISSUE THREAD

**Issue by AhmedSalih3d** [rlguy/Blender-FLIP-Fluids-Beta#17]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724333/test_case_viscous_net65.zip)

I ran the viscous_net succesfully on my laptop. Looking forward to trying out the more advanced tool, when this gets approved hopefully. I didn't experience other issues, than if I wanted to cache my results in a dropbox folder it would make an error since a sharing violation would occur. The simple fix was to store on harddrive instead.

**Comment by rlguy** [comment]
Thanks AhmedSalih3d!

I checked your results and it looks like the test ran okay, but you are affected by issue #7. The simulator is choosing your integrated graphics chip.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
