### ISSUE TITLE
[Feature Request] Split surface simulation from whitewater and meshing steps

### ISSUE THREAD

**Issue by Getrad** [rlguy/Blender-FLIP-Fluids-Beta#171]
I'm not sure if it's possible, but it would be great to optionally separate out the surface simulation so it can be run once, and then used to drive whitewater generation and mesh generation ans separate tasks.

For example, say I've got a nice simulation of an object splashing into a pool of water, but there's just not as much spray as I'm looking for.   Currently, I need to tweak a few of the white water settings and then simulate the whole thing again.    It would be great to just use the existing surface data to re-run only the white water calculations.

Similarly, splitting the surface meshing into a separate process could open up the future possibility of blending variable resolution simulations, so the detail can be targeted where it's needed.   Overlapping domains could even offer up options to blend the sim data, add, subtract, etc...

Those are certainly not small feature requests, if they're possible, but potentially something to think about as the addon develops.

**Comment by rlguy** [comment]
Thanks for the input! This is something that would be very useful, but not very feasible at the moment. More discussed in this issue: #157
