### ISSUE TITLE
[Test Case Results] dreamswan

### ISSUE THREAD

**Issue by dreamswan** [rlguy/Blender-FLIP-Fluids-Beta#174]
Ran fluid_in_an_invisible_box.blend at a resolution of 300 and everything seems to have gone well.
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1766663/test_case_fluid_in_an_invisible_box300.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by dreamswan** [comment]
Not a problem! Here's the rest of the resolutions for that same scene.

[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1784232/test_case_fluid_in_an_invisible_box100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1784230/test_case_fluid_in_an_invisible_box200.zip)
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1784231/test_case_fluid_in_an_invisible_box400.zip)

**Comment by dreamswan** [comment]
Should I be seeing more usage than this during baking
![clipboard 1](https://user-images.githubusercontent.com/13227338/37050905-bb803f94-213a-11e8-933b-265f99dc635f.png)
?

**Comment by rlguy** [comment]
Thanks for the results, dreamswan! We've been noticing that the simulator is running slower than expected for users with hardware capable of running many threads. There's a note on this here:

https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal

We're collecting data from users with this kind of hardware so that we can hopefully figure out how to optimize the simulator better. Your results will certainly help us with that!

**Comment by dreamswan** [comment]
Makes sense thanks! Some more test cases finished.

[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1798859/test_case_viscous_net65.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1798860/test_case_viscous_net100.zip)
[test_case_viscous_net150.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1798861/test_case_viscous_net150.zip)
[test_case_viscous_net200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1798858/test_case_viscous_net200.zip)
