### ISSUE TITLE
[Feature request] adaptive liquid / workflow discussion

### ISSUE THREAD

**Issue by TripleDots** [rlguy/Blender-FLIP-Fluids-Beta#175]
So I was researching the different ways of fluid simulation methods to get a better understanding on how different methods work. A second reason was because I tried making an Pirates of the Caribbean type entrance as seen here https://youtu.be/PEaZ5XUe0Mk?t=20s
but left without any hard drive space left because I need the smaller size particles (thus higher resolution) to interact around the ropes and other smaller details correctly. For now I am trying a method where I blend several fluid sims together for different detail types to see if that works (which it seems to do!)

After a bit of googling I came across this very interesting paper from the Houdini forums.

I wonder if this is possible and if not, it's still an interesting read. Even for people like me who don't necessarily understand the underlying calculations!

Paper:

http://pub.ist.ac.at/group_wojtan/projects/2013_Ando_HALSoTM/index.html

**Comment by rlguy** [comment]
It's an interesting paper and a great video! One of the authors, Nils Thürey, wrote Blender's internal Elbeem simulator and also authored the Mantaflow simulator.

Unfortunately this kind of simulation technology likely won't be added to this plugin. It would involve restructuring and rewriting much of the fluid engine which would take a very long time. We just don't have the resources and at the moment, the required knowledge, to implement this.

If you're interested in learning about this kind of research, you may want to check out the [Two Minute Papers](https://www.youtube.com/user/keeroyz/videos) Youtube channel. There are many videos that summarise interesting research papers, many of them related to simulation and computer graphics.

**Comment by RevDr** [comment]
Whilst having random thoughts I did wonder if it would be possible to have two domains types: an overall domain and within in it, a subset, active domain.  Only the area inside the active domain would be simulated.  However the active domain can move.  This would be helpful if you wanted to track in camera the active domain and object (say a boat) in a longer shot moving through a fluid whilst keeping computation down a bit.

Anyway may not possible to implement as  is but just offering it up as an idea.

**Comment by rlguy** [comment]
Good thinking, but there will be some problems! The physics and boundary conditions at the edge if the inner domain would be inconsistent since the outside fluid is not being simulated. This can lead to weird behaviour at the edges or simulation blowups/explosions. A fix for that is to simulate the outer fluid at a lower resolution, but then there are performance problems since there is high resolution fluid in a low resolution simulation. To fix that would be to convert the outside fluid to larger particles, but then we end up with something complicated that resembles a simplified version of the original 'adaptive liquid' paper in this thread.

**Comment by rikere** [comment]
You're on the right track to doing it in Blender. My approach would be to lock down the animation, then do multiple scenes/files, and each one contains one or a set of smaller fluid sims. Use ocean sim/dynamic paint for the main ocean, then possibly use dynamic paint with each of the fluid sims to allow it to create ripples when it touches the ocean (but don't set the ocean as a collider). For bigger shots, do one big sim and tweak the model's shaders to reflect the presence/abscence of wetness/water until you get back to a closer shot.

Once everything is composited together, no one's going to know the difference. In the FX industry, for decades, they just shot explosions and splashes and threw them over the footage (that's actually how they did some fog fx in coraline, real fog), so stitching it all together would definitely work.

**Comment by rlguy** [comment]
I'll be closing this discussion to clean up the issue tracker!
