### ISSUE TITLE
[Test Case Results] tobkum

### ISSUE THREAD

**Issue by tobkum** [rlguy/Blender-FLIP-Fluids-Beta#177]
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1771125/test_case_lighthouse125.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1770980/test_case_fluid_in_an_invisible_box100.zip)

Different computer:
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1771144/test_case_lighthouse125.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the tests ran without errors on both systems.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
