### ISSUE TITLE
[Test Case Results] ocheret

### ISSUE THREAD

**Issue by ocheret** [rlguy/Blender-FLIP-Fluids-Beta#178]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1772908/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by ocheret** [comment]
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1775182/test_case_fluid_in_an_invisible_box400.zip)

**Comment by ocheret** [comment]
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1775750/test_case_lighthouse125.zip)

**Comment by ocheret** [comment]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1775921/test_case_viscous_net65.zip)
