### ISSUE TITLE
[Bug] libblpyfluid.dll.a Not Designed to run on Windows

### ISSUE THREAD

**Issue by rikere** [rlguy/Blender-FLIP-Fluids-Beta#179]
I attempted to run the FLIP plugin on one of my weaker machines (always fun to see what even low power can do) and I got the following error:

![image](https://user-images.githubusercontent.com/22123117/36879600-95ece418-1d92-11e8-89de-be9c43c351a8.png)

System Specs:
Intel i3-2120T
Integrated/Intel Accelerator GPU
6gb Ram
Windows 10 Home 64bit
5400RPM HDD as well to further stress it

I am not sure why that error came up at all.

**Comment by rlguy** [comment]
You may need to update graphics drivers. See issue #6.

Let me know if that fixes the problem.

**Comment by rikere** [comment]
I will see what I can track down. I'm not sure this system is even capable of using OpenCL.

**Comment by rlguy** [comment]
Haven't heard a response, I'll be closing this issue.
