### ISSUE TITLE
[Test Case Results] lumpynose

### ISSUE THREAD

**Issue by lumpynose** [rlguy/Blender-FLIP-Fluids-Beta#181]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1776339/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by lumpynose** [comment]
The first email from you with the subject "You've been invited to join the
FLIP Fluids Beta!" has a passcode but in the sentence " Please try to
access your Dropbox folder folder now and let us know if you have any
problems gaining access." the blue Dropbox folder text is not a link; the
href= part is blank.

**Comment by rlguy** [comment]
Woops, sorry about that! Not sure how that happened. I re-sent you another invite and now the links should be working.

Didn't realize 'folder folder' was written double.

**Comment by lumpynose** [comment]
That fixed it; thanks.
