### ISSUE TITLE
fluid domain child object fluid surface didn't resize?

### ISSUE THREAD

**Issue by lumpynose** [rlguy/Blender-FLIP-Fluids-Beta#182]
I started a simulation but realized that I needed another object that was bigger than the domain so I resized the domain, but then when I ran the simulation the fluid surface object that's a child of the fluid domain didn't get resized when I applied the scale to the fluid domain.  I had the Bake Export Settings on Force; I don't know if that's what caused the problem. Perhaps it's something that needs to be documented.

**Comment by rlguy** [comment]
Hey, there can be some issues with cache meshes loading correctly of scale/location is applied to the domain. Quick fix should be to delete the child object(s). They will regenerate.

Documented at the end of this page:
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Object-Settings

**Comment by lumpynose** [comment]
Ok, thanks.  I skipped over that note in the docs.
