### ISSUE TITLE
 [Test Case Results] GottfriedHofmann 

### ISSUE THREAD

**Issue by GottfriedHofmann** [rlguy/Blender-FLIP-Fluids-Beta#19]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724700/test_case_fluid_in_an_invisible_box100.zip)

**Comment by rlguy** [comment]
Thanks GottfriedHofmann!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
