### ISSUE TITLE
Cache Operators: virtual append - a bit like pre roll.  

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#194]
Hi,

As well as move, rename and copy I was wondering if it might be possible to have something along the lines of a 'virtual' append operator (not sure that is the correct frame) - which would function as a precached pre roll.

Why would this be helpful?  Take a case with a sim which will be 250 frames.  You are happy with with the first 150 frames but are working on obstacle movement from frame 150 onwards.   

Rather than keep redoing the whole sim - with this functionality it would be possible to cache first 150 frames into path ..\SimPathA and then append to that into ..\SimPathB.   When playing back frames 0 to 150 could use SimPathA and frome 150 on SimPathB.

Whilst tweaking animation resetting the cache would only delete frames from SimPathB and then baking would bake from (in this case) frame 150.

Now I realise this is kind of possible already using the Copy cache operator and then using the copied cache and continuing to bake.  However, in the case when you might want multiple different sims to all start with the same first 150 it would be more economical for disk space not to require 150 frames of duplicated data.

**Comment by rlguy** [comment]
The implementation of this feature will be quite related to this feature (issue #195) so I'll be merging this into the other issue.
