### ISSUE TITLE
[Issue] High res baking takes extremely long to stop/pause

### ISSUE THREAD

**Issue by TripleDots** [rlguy/Blender-FLIP-Fluids-Beta#197]
When stopping a 400 res bake (or higher) it takes longer to stop/pause than to bake a 200 res scene.
Sometimes it feels like it never stops making me restart Blender.
The simulation is stopped (no resources are being used.) The button just stays greyed out for a long time.
The higher the resolution the longer it takes.

**Comment by rlguy** [comment]
The Mantaflow simulator also has a similar problem and the reason for it is explained here by Sebbas: https://github.com/sebbas/BlenderMantaflow/issues/17

The quick explanation is that the simulation thread can only stop itself at the end of computing a frame. There isn't a simple way to terminate the simulation thread while it is computing the frame. Higher resolutions take longer to finish computing a frame.

The quickest way to terminate the simulation is to quit Blender. This is safe as long as the button displays **Cancelling... Safe to quit Blender**. If the simulator is current writing data to disk, then the button will display **Cancelling... Do NOT quit Blender** and quitting Blender could corrupt the cache.

**BUT** if the frame is finished and the button is still greyed out, this is a bug. Would you be able to test this and let me know if the button is still greyed out after the simulation stops?

If the simulation has stopped the Blender System Console should look like this:

![untitled](https://user-images.githubusercontent.com/4285191/37364255-38680254-26b7-11e8-9f8e-d965ef07e615.jpg)

If the frame is still in progress, then the console may look like this:

![untitled](https://user-images.githubusercontent.com/4285191/37364326-6778f6ac-26b7-11e8-8e1e-0d8e930c04c2.jpg)

And the console should continue spooling messages until the frame ends.

**Comment by rlguy** [comment]
Haven't heard back, so I'll be closing this issue.
