### ISSUE TITLE
Minor text display issue in Mesh Stats.

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids-Beta#198]
Probably just a minor thing but I noticed that the units for the mesh statistics cuts off pretty early and can probably be adjusted a bit better for smaller side bars.

https://gfycat.com/PoshIllegalAntbear
Total could probably be put below, maybe bold it to make it stand out.
Or if the split is wanted, then the spacing could be adjusted.

**Comment by rlguy** [comment]
Thanks for the suggestion, this will be included in the next version (**0.1.3b**)! I have moved the total to a separate line below. Unfortunately Blender has no way to set bold text as far as I know.
