### ISSUE TITLE
Buoyancy/Water interacting with objects?

### ISSUE THREAD

**Issue by camcam2015** [rlguy/Blender-FLIP-Fluids-Beta#199]
Just a quick question/wishful thinking... Currently the addon handles obstacles by looking at just the keyframe/animated mesh data and simulating the movement of the water being affected by that. Would it be remotely possible in a future build for objects to dynamically be moved by the water itself, as if it were a rigid body (ex. a rubber ducky in bathwater or a ship floating on a river)?

**Comment by rlguy** [comment]
This won't be possible in the addon, unfortunately. Only scripted obstacles will be supported. This means the obstacles can push around the fluid, but the fluid will not be able to push around the objects. 

This feature would require interleaving the rigid body and fluid simulation baking calculations, which is not possible with Blender at the moment. The alternative would be to include our own rigid body simulator (such as Bullet) into the addon and transfer rigid body simulation data back into Blender, but this would be too much work.
