### ISSUE TITLE
[Test Case Results] FLIPFluidsBetaTester

### ISSUE THREAD

**Issue by FLIPFluidsBetaTester** [rlguy/Blender-FLIP-Fluids-Beta#2]
Hey, I ran the fluid_in_an_invisible_box.blend test case at 100 resolution and I think it ran okay. Here are the results:

[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1683687/test_case_fluid_in_an_invisible_box100.zip)

**Comment by rlguy** [comment]
Thanks FLIPFluidsBetaTester! 

I checked your results and it looks like the test ran without errors.

I have updated your DropBox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your DropBox folder. 

I will be closing this issue. Please reopen this issue if you submit more test case results.

**Comment by FLIPFluidsBetaTester** [comment]
I finished running the rest of the resolutions for the fluid_in_an_invisible_box.blend test case. Here are the results:

[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1683714/test_case_fluid_in_an_invisible_box200.zip)
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1683715/test_case_fluid_in_an_invisible_box300.zip)
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1683713/test_case_fluid_in_an_invisible_box400.zip)

There was a problem with the 400 resolution test. The simulation baking stopped at frame 502 with an 'invalid argument' error. I forgot to take a screenshot of the full error. But I was able to resume the simulation and continue baking until the test finished. Hope this info helps.

**Comment by rlguy** [comment]
Thanks for submitting these test cases!

I was able to figure out what the issue was with the 400 resolution test. The simulator was trying to operate on a thread that did not exist. The issue has been fixed in the latest test suite version.

It looks like all tests ran to completion and the data for the 400 resolution test is still usable!

**Comment by FLIPFluidsBetaTester** [comment]
Hey, here's the test case results for the rest of the scenes:

[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687777/test_case_viscous_net65.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687778/test_case_viscous_net100.zip)
[test_case_viscous_net150.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687779/test_case_viscous_net150.zip)
[test_case_viscous_net200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687780/test_case_viscous_net200.zip)

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687781/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687782/test_case_cascading_water_feature200.zip)
[test_case_cascading_water_feature300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687783/test_case_cascading_water_feature300.zip)
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687784/test_case_cascading_water_feature400.zip)

[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687785/test_case_lighthouse125.zip)
[test_case_lighthouse250.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687786/test_case_lighthouse250.zip)
[test_case_lighthouse375.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687787/test_case_lighthouse375.zip)
[test_case_lighthouse500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1687776/test_case_lighthouse500.zip)

**Comment by rlguy** [comment]
Thanks for completing all of the test cases! These results will help us optimize the simulator to run better on systems like yours!
