### ISSUE TITLE
[Test Case Results] hrisek

### ISSUE THREAD

**Issue by hrisek** [rlguy/Blender-FLIP-Fluids-Beta#20]
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1724743/test_case_cascading_water_feature200.zip)

**Comment by rlguy** [comment]
Thanks hrisek!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
