### ISSUE TITLE
[Scene Troubleshooting] Fluid clipping.

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids-Beta#200]
Testing a bit more and I seem to hit another problem, which I actually also had to a degree in the pipe burst test I did.  

![blender_2018-03-10_21-43-07](https://user-images.githubusercontent.com/8568089/37246576-293e7bbc-24ac-11e8-8512-fbdb8e9e233b.png)

Up until this point I actually managed to contain the fluid just fine, a minor issue where it already clipped before.
![blender_2018-03-10_21-44-49](https://user-images.githubusercontent.com/8568089/37246579-50c273d2-24ac-11e8-86fd-464193386135.png)

Just further on when more movement in the scene happens in breaks through the container.
Container uses a bit of Expand, 0.01 which might be too little but I'm not sure how that value even works. Any clarification of what "some value" means? Is it blender units?

Here is the part where most of the fluid just ignores the first container:
https://gfycat.com/MagnificentLimpingBrant

The settings are up in the first screenshot. With how high I set the Substeps I already got quite the big bake time increase, ~80hours total.  
Before this one I actually set it even higher, I think around 10 min, 15 max but then I would get like 100 days+ of bake time.  

Was wondering which settings would help here the best, ultimatively substeps can solve it but they just increase the bake time way too much.
Also in relation to the scene and baking time, does Subdivisions increase baking time or precision?
I could do more testing in relation to the single settings but I rather ask here first because that can take quite some time.

**Comment by rlguy** [comment]
This is related to the thin obstacles issue (#148). The obstacle walls look very thin compared to the resolution you will get with that domain size. In general, I wouldn't recommend setting the min substeps higher than 4. I would instead make changes and rework the scene to keep computation times down.

It looks like your domain is very very large compared to the active fluid area. The simulator must make calculations all throughout the domain, so areas where fluid isn't interacting with anything will waste computation, use more RAM, and increase bake times. I would recommend making the domain as small as possible. Small enough to just contain your fluid effect. Lower the ceiling of the domain if the fluid wont be splashing all the way to the top. Decrease the width and depth of the domain if possible. This will maximize performance.

Decreasing domain size will also concentrate the grid resolution (smaller cell size) and help prevent fluid from slipping through thin walls. Try turning on the 'Display Grid' feature in the [Debug Panel](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Debug-Settings). If your CFL number is set to 4, then obstacle walls should be slightly larger than 4 grid cells in width to prevent fluid from moving through the walls. The CFL number limits the fluid particles to only move a certain number of gridcells per substep. If the speed of the fluid will cause particles to move more gridcells, then the simulator will adaptively increase the number of substeps for the frame.

Hope these tips help! Let me know if you have any questions.

**Comment by Mitsuma** [comment]
This actually helped a lot. While I still fight with clipping (might have to redo the container) I actually can simply crank up the resolution (testing how much I need at the moment.) 
With smaller domain and checking with the grid, in addition to keeping the substeps at 4, I already get a lot lower bake times. 
So the increase in resolution is not a real problem.

**Comment by Mitsuma** [comment]
![2018-03-11_16-34-55](https://user-images.githubusercontent.com/8568089/37256328-520a239a-2559-11e8-8abe-743968d27de0.png)
![blender_2018-03-11_16-29-38](https://user-images.githubusercontent.com/8568089/37256331-53b9966c-2559-11e8-8605-57b10f87a53a.png)
![blender_2018-03-11_16-31-13](https://user-images.githubusercontent.com/8568089/37256333-554c7698-2559-11e8-9444-9f95b5af54f8.png)

Pretty pleased with the current results, although I have noticed a few times that FLIP tends to create those small "ball drops". They look a bit worse in still then in motion.
I use the built in water preset, was wondering if there is a way to make it more uniform.

**Comment by rlguy** [comment]
Hey, glad to hear it is working better.

I was wondering what exactly you mean by the small "ball drops":

1. The drops slipping through the walls in the first image?
2. The small drops flying around in the air in the 2nd/3rd image?
3. The small isolated drops laying on the ground?
4. All of the above?

**Comment by Mitsuma** [comment]
![](https://i.imgur.com/vJmKMNu.png)
This area for example, maybe this is an artifact of using 2x subdiv but I seen it create those a couple of times. They are not whitewater particles.

**Comment by rlguy** [comment]
Those drops are the individual fluid particles. At a subdivision level of two, there will be enough mesh detail to see every simulation particle in the mesh. I think this is unavoidable at the time. You may try tuning the PIC/FLIP ratio. A higher ratio will create a less accurate and less chaotic simulation that might keep particles closer together and reduce the number of stray particles. I haven't experimented with the value too much, but I would suggest something around 0.2-0.3 to start with.
