### ISSUE TITLE
Modfiers which reduce poly size do not reduce exporting time

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#201]
Hi,

I have a a  moving object which I want to use in a sim.

It takes 1 minute to export and start baking frames.

I don't really need the resolution as high for sim as I do for render.  Therefore I use a remesh modifier (or a decimate modiifer) to reduce the number of polys.

However it still takes 1 minute to export baking frames.

If I apply the modifier the export time takes 15 secs to export.

Not sure why the reduction in time requires the modifier to be applied.

Thanks

**Comment by rlguy** [comment]
Hey,

This is working as designed. When a modifier is in the stack, Blender must apply the modifier when evaluating the mesh for export. This will happen on each frame of export and that is why it takes extra time. If the modifier is applied to the mesh, then the modifier never needs to be evaluated.

**Comment by RevDr** [comment]
Hi,

When I play back the object with the modifier in the viewport there is no noticeable change in playback speed.  However, there is a noticeable change in export.

Is that because Blender internally knows it does not need to evaluate the modifier stack where as an external plug in does not?

**Comment by rlguy** [comment]
Hey,

I assume Blender has optimizations for evaluating the modifier stack for the viewport. There is also more going on during the mesh export stage vs viewport playback. The mesh is being triangulated, temporary objects are being created/destroyed, mesh data is being rearranged, speed vectors are being calculated.
