### ISSUE TITLE
[Feature Request] Enable FLIP Fluid obstacle/inflow/outflow/fluid for all selected objects

### ISSUE THREAD

**Issue by vmxeo** [rlguy/Blender-FLIP-Fluids-Beta#204]
Small enhancement request - Add an operator that enables FLIP Fluid obstacle for all selected objects. (Unless there's already a better way that I'm missing)

**Comment by rlguy** [comment]
Hey vmxeo,

I looked this up, and it turns out there is an easy way to do this in Blender!
1. Select all obstacles
2. Click 'Enable'
3. Right click on 'Enable' and select 'Copy To Selected'

![untitled](https://user-images.githubusercontent.com/4285191/37365250-2bf094d4-26ba-11e8-804b-c19279605622.jpg)

This will copy the enabled property to the rest of the selected objects

**Comment by vmxeo** [comment]
That was the first thing I tried :)

There's two issues with it, one minor and one major:

1) Running _Copy To Selected_ doesn't immediately show the settings, though they seem to be active. You have to press the "FLIP Fluid" button in the Physics UI panel. 
![image](https://user-images.githubusercontent.com/19572685/37366808-e1739afa-26d7-11e8-839b-46911daff772.png)

2) It also causes the FLIP fluid domain to crash on bake.
`
13-Mar-2018 15h59m58s addMeshObstacle: 0x18b918c0c40
Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1137, in bake
    __initialize_fluid_simulation(fluidsim, data, cache_directory, bakedata)
  File "C:\Users\Josh\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 564, in __initialize_fluid_simulation
    data.obstacle_objects = __add_obstacle_objects(fluidsim, data, bakedata)
  File "C:\Users\Josh\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 468, in __add_obstacle_objects
    obstacle.inverse = __get_parameter_data(obj.is_inversed)
  File "C:\Users\Josh\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 89, in __get_parameter_data
    raise IndexError()
IndexError
Info: Error Baking Fluid Simulation
Info: Unknown error. See system console for error info.
`

Digging into the data-blocks, it appears the _flip_fluid.obstacle.property_registry.properties[0].path_ doesn't get populated when you run a _Copy To Selected_.

**Comment by rlguy** [comment]
Alright, I think I misunderstood the issue! I assumed all objects were already 'FLIP Fluid' objects and that you wanted to modify the 'Enabled' attribute:

![untitled](https://user-images.githubusercontent.com/4285191/37370922-f0d755b6-26ca-11e8-9825-fb30b2101279.jpg)

I'll add operators to add all selected objects as obstacle and also inflow/outflow/fluid.

**Comment by rlguy** [comment]
I have added these operators to the FLIP Fluid toolshelf menu:

![add_remove_objects](https://user-images.githubusercontent.com/4285191/37440741-4f18f080-27bb-11e8-90b3-72dc1deda786.jpg)

This will be included in the next beta version (**0.1.3b**)
