### ISSUE TITLE
Viscosity ideas/enhancements

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#205]
I see the viscosity parameter is on the domain, acting as a global parameter. Would it be possible to have the viscosity parameter on the emitter itself so that you could have say 3 emitters, each with their own viscosity values, interacting with one another? So a melted chocolate, topped with a thicker chocolate and lastly a thick syrup. https://vimeo.com/89847246  

Another thing would be variable viscosity. https://vimeo.com/102554547 
So being able to control the viscosity of an object with textures or ramps. 
To handle effects like [melting](https://vimeo.com/206120889) and [lava.](https://vimeo.com/124184280)

Amazing work guys! I am having such a blast using this addon! I know this is no easy feat! These are just ideas after using Houdini and what would amazing to have inside of Blender

**Comment by rlguy** [comment]
Hey k1ff,

Variable viscosity features are something I have thought a lot about and am excited to get into this simulator in the future! I'll be merging these ideas with this issue: #189 

Great to hear how much you are enjoying the addon!
