### ISSUE TITLE
Beta instructions

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#21]
Hi,

This is really simple - however the download contains a zip withing a zip.  

You have to unzip the first file and install the inner zip (if that makes sense) it's not a problem - just not 100% clear.

Thanks

Rob

**Comment by rlguy** [comment]
Hey RevDr,

Let me know which download you are referencing and I can check this out. Do you mean the Test Suite addon?

**Comment by RevDr** [comment]
ok - no problem.

**Comment by rlguy** [comment]
Okay, I see what you mean now! I didn't notice that if you downloaded the entire version folder directly it would download as a .zip. This could be confusing so I have removed the subfolder and placed the addon directly in the top level directory.

Thanks for pointing this out!

**Comment by RevDr** [comment]
No problem.

Excited to have run my first test (fluid in an invisible box) at resolution 100.

Currently running again at 300 – which should hopefully finish in time for my bed time tonight.

This should enable to run the 400 test overnight.

Rob
