### ISSUE TITLE
Transfer textures from fluid object 

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#210]
For example, I have an object that is textured. Then I make it the fluid object. Will it be possible that the fluid object get's the textures transferred to it? Just thinking about effects like [this](https://vimeo.com/178384597)

**Comment by rlguy** [comment]
This will likely not be added as a feature. Texturing the surface mesh and simulating the texture advection through the flow of the fluid is quite complicated and will require too much time/resources to implement.
