### ISSUE TITLE
Inaccurate viscosity, particles stopping/starting

### ISSUE THREAD

**Issue by Blaast** [rlguy/Blender-FLIP-Fluids-Beta#211]
More details tomorrow, but I tried making a simple simulation, no special effect, just a 3 cubes including one quickly edited : https://drive.google.com/open?id=1aikCkPbY1y3VhLttjL5J57YTDUkjrxkx
> I've tried reinstalling FLIP 1.2b twice, using addon manager
> I will try a complete remove of FLIP tomorrow, probably, by hand, and reinstall.
> I will try it too on other computers
> I will upload .blend when I will get time (right now it weights 125 MB :/ )

**Comment by rlguy** [comment]
I don't know what that is either! Let me know when the .blend file is uploaded, it will be required for testing. Feel free to delete all data that aren't the simulation objects to keep filesize down.

**Comment by Blaast** [comment]
Here is the blende file (interesting thing BTW : it saves the meshin the frame in the file, so if I selected a baked frame : it weights around 128 MB, but at a non baked frame : 777kB) https://drive.google.com/open?id=15wwj8m9-U98tnI217yt5Onx1_lPzXEu5

I haven't tried yet to clean reinstall FLIP, and I defintly think it is something related to the install.

I've had strange things happening, such as "vibrating" fluids in the last tests : https://drive.google.com/open?id=1hzImv_M0B_gyh_hlR4PaL6DYtVAn8L4C

On another subject : worked great before ! https://drive.google.com/open?id=1ejAABbsmGIuHCefU3e0eEDy37WWfh9Xt

**Comment by Blaast** [comment]
Fluid vibration file : https://drive.google.com/open?id=1jJHQeoC7INOKOdRlAc1tkmIJMjMNRIhP

BTW, is it possible to simulate both fluid collision and Archimede effect ? ( I mean physics of falling and floating in the same simulation)

**Comment by rlguy** [comment]
Thanks for the .blend files!

> I've had strange things happening, such as "vibrating" fluids in the last tests : https://drive.google.com/open?id=1hzImv_M0B_gyh_hlR4PaL6DYtVAn8L4C

This is an issue with the small world scale size. A size of 0.20m is quite small for the simulator and can result in unstable/inaccurate simulations. Increasing the _Min Substeps_ value to 3 or 4 in the [Advanced Settings](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings) panel should increase accuracy and prevent the surface from 'vibrating'.

Note: The simulator works best at world sizes greater than **2.0m**.

> BTW, is it possible to simulate both fluid collision and Archimede effect ? ( I mean physics of falling and floating in the same simulation)

This is not possible. Explained in this issue: #199 

---

I still need to take a look at what is causing the issue with the viscous scene. I'll keep you updated in this thread!

**Comment by rlguy** [comment]
I have had time to check this out and have found that it is caused by a limit of the viscosity solver at that high of a domain resolution. The viscosity of 5 at a world scale of 1m is too viscous for the solver to handle and it ends up failing when it can't find a solution. 

The fix is either to reduce domain resolution or reduce the viscosity value. These things will put less of a load on the viscosity solver.

Note that the viscosity value is dependant on world size/scale. A value of 5 at 1m is much thicker than a value of 5 at 10m. Increasing world scale will also put less load on the viscosity solver.

**Comment by Blaast** [comment]
Thanks, good to know !
