### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by lumpynose** [rlguy/Blender-FLIP-Fluids-Beta#212]
Here's the console output:
[console.txt](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1822283/console.txt)

Here's the blend file:
http://pasteall.org/blend/index.php?id=49171

**Comment by rlguy** [comment]
Hey, this is an 'out of memory' error. The addon should display this popup, but depending on the system, Blender may quit/crash and you would not have a chance to see this:

![untitled](https://user-images.githubusercontent.com/4285191/37606276-53010bde-2b52-11e8-8db0-1395d33e8287.jpg)

I am wondering how much RAM you have on this system? Do you get this error at a lower resolution (150 or 250)?

**Comment by lumpynose** [comment]
I have 16 gig.  I did try lowering the resolution but then the fluid had a bunch of holes in it.  I think something got "corrupted" somehow but I don't recall making any changes to the settings.

**Comment by rlguy** [comment]
Finally got around to testing this further. Seems like it is just a regular out of memory error.

**Comment by lumpynose** [comment]
Ok, thanks for letting me know.
