### ISSUE TITLE
Resume Baking from frame

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#213]
Hey guys,

Would it be possible instead of Resume Baking from the frame you stop baking, could it also be possible to enter in a frame where you want to resume baking from. For example, I like the first half of the simulation, but then I go for a coffee and come back and I don't like the middle but it's already near the end. So I stop baking the simulation and it only allows you to resume from the frame you stopped the simulation. Would be great to be able to choose a frame to resume the baking form earlier in the timeline.

**Comment by rlguy** [comment]
Hey k1ff,

There is a feature request for this here: #195. It looks like I accidentally closed 195 and didn't notice until just now! I have reopened the issue.
