### ISSUE TITLE
 Fluid Viscosity value = Poise?

### ISSUE THREAD

**Issue by vmxeo** [rlguy/Blender-FLIP-Fluids-Beta#214]
A (hopefully) quick question - Does the Fluid Viscosity value correspond to a physical unit value (i.e. poise)?

**Comment by rlguy** [comment]
It's just a number and doesn't correspond to any physical unit values.

> The viscosity value in this simulator doesn’t relate to a real life physical quantity. So if you copy a real life viscosity value into the simulator, it may not match the visual thickness of the real life liquid.

**Comment by vmxeo** [comment]
Then as a future feature suggestion, if it was tied to a physical value, it'd be easier to dial in a known viscosity for a given material:
https://en.wikipedia.org/wiki/Viscosity#Other_substances
