### ISSUE TITLE
Suggestion : Force effectors

### ISSUE THREAD

**Issue by Blaast** [rlguy/Blender-FLIP-Fluids-Beta#218]
Hi ! Maybe it is already implemented somehow that I've haven't found during my tests, but if it's not, I think it could be great to have forces working in FLIP ! Wind, simple force, magnets, curves, etc :)

Would allow many effects simulations, like for exemple an object hovering above water (helicopter etc), or follow a shape !

I don't know if it's possible though, but anyway, I think it would allow a wider range of effects to be simulated.

Just saw it's related to this issue : https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/164
Any idea when it would be in test ?

**Comment by k1ff** [comment]
I think that would be great!

**Comment by rlguy** [comment]
This is a planned feature. From issue #164:

> It is planned to add support for Blender’s force types. This will probably be the next large feature added after release.

This is quite a large feature, so it will be something that is implemented after release and not during this beta.
