### ISSUE TITLE
Bug : Render waiting frame simulated ?

### ISSUE THREAD

**Issue by Blaast** [rlguy/Blender-FLIP-Fluids-Beta#219]
Hi, I'm not 100% sure it's a FLIP-related issue, but I'm currently baking and rendering at the same time a project. The GPU that doesn't seem to be used for FLIP is used for render, as the amount of cores allows for no downgrading in performances (I think, and it seem fine after a few tests).

But, I've noticed the writing time is very high for the render to be saved, even though the output is in .jpg (yes I know yurk, not pro, etc, but it was just for a quick render test and I didn't want to populate too much my drives)

I think, though not sure, that blender is waiting for the frame baked in the simulation to be output to output the rendered frame. I could be wrong, though.

**Comment by Mitsuma** [comment]
Check your RAM usage. During most of the stuff I did I simply max out my RAM all the time.
So to not crash Windows will write on your pagefile, benefit is you don't crash, big downside is that certain actions take way longer, especially if that pagefile is on a HDD.

**Comment by Blaast** [comment]
It's not that, I'm only at around 50% RAM load (24GB out of 56GB), and pagefile has been disabled :/
Thanks for the hint though !

**Comment by Mitsuma** [comment]
Ah okay, I would honestly still recommend enabling the pagefile. 56GB is a lot but in the rare case it does overfill your programs don't just crash, useful to have.

**Comment by rlguy** [comment]
If this is an issue, it will be related to Blender/Windows and not the FLIP Fluids addon. The simulator is run in a separate thread which runs independently from Blender and does not synchronize with Blender or use the Blender Python API.

The simulator does write mesh/cache data to the filesystem, so this could be the OS waiting for filesystem write operations to finish.

**Comment by Blaast** [comment]
Thanks !
On the other end, would it be possible an option to enable the "wait render frame until next frame is simulated" ? I've reached a point where my sim per frame lasts 400s but render is 200s, even with the OS related issue, render catch up with the sim after ~ 50frames.
So, do you think it could be a nice option ?
Thanks again for your job :)

**Comment by rlguy** [comment]
This has been something we have thought about and have wanted to implement. Right now, Blender does not have addon functionality to pause/wait/continue animation renders which would make this simple to add. I have read that this might be added in the future.

To add this feature, we may end up having to write our own animation render system that renders frame by frame and waits for baking to finish. So it is possible that this will be a feature in the future!
