### ISSUE TITLE
Test version: Display settings not working properly

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#22]
Hi,

Changing the viewport display options seems to have no effect between final/preview/none

Neither do they seem to make a difference on different elements - for example fluid_surface.

Have only run 100 resolution test so far.

Come to think of it - what does is the difference between the display settings on the domain and the different elements (i.e. surface) mean?

Thanks

**Comment by rlguy** [comment]
Hey RevDr,

The viewport display options seem to work for me. One note: once changing the display mode, you will need to reload the frame. Changing the frame, or re-entering the frame number in the timeline will trigger a reload. On some test scenes, you'll see a larger difference between preview/final at higher resolutions. Does this work for you?

The display settings on the surface/foam/bubble/spray are all linked to the display settings in the domain. For example, if the _**fluid_surface**_ object is selected, the _**Surface Viewport Display**_ is linked to the _**Surface Viewport Display**_ setting in the domain. If _**whitewater_bubble**_ object is selected, the _**Whitewater Viewport Display**_ is linked to the _**Whitewater Viewport Display**_ setting in the domain.

**Comment by RevDr** [comment]
Will check it works when current test sim finished (est 3 hours to go).  Is there anyway to force the update without changing the frame?

The linking of options makes sense.

Thanks

**Comment by rlguy** [comment]
There isn't a way to force the update without changing a frame at the moment. I have added a feature request for this here: issue #25

**Comment by RevDr** [comment]
Just to confirm - your workaround (change the frame) works for now.

Thanks
