### ISSUE TITLE
[Feature Request] Influence control for 'Add Object Velocity to Inflow' parameter

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#220]
Hey guys,

I would like to ask if adding an influence slider to Add Object Velocity to Inflow.
That way it's not just an on or off option but an on and off + % of how much of the object velocity to use.
I am having an issue where I am using Object Velocity but the velocity is far too much! Is there a way to control how that?

Thanks so much!

**Comment by k1ff** [comment]
This will be huge! Could achieve melting effects this way and so much more. Awesome, thanks so much!

Kind regards,

**Comment by k1ff** [comment]
Replied on the wrong thread. But this will be a great feature as well!!

**Comment by rlguy** [comment]
This setting has been added for both inflow and fluid objects! It will be included in the next version (**0.1.3b**) which should be available by March 31st.

> **Object Velocity Influence**
> Amount of velocity that is added to the inflow fluid. A value of 1.0 is normal, less than 1.0 will dampen the velocity, greater than 1.0 will exaggerate the velocity, negative values will reverse velocity direction.
