### ISSUE TITLE
Access to particle info for shader

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#221]
Is there a way to access the particles so that they can be used in the shading? Particle age and velocity would be great to be able to use in shading!

**Comment by k1ff** [comment]
Also, if that particle data could drive things like viscosity. So particle age could harden the fluid the older it becomes. Born with no viscosity and then as time goes on viscosity increases but on a particle level.

**Comment by rlguy** [comment]
Unfortunately there is not a way to access particle data for shading with an addon at the moment. Perhaps in the future this will be possible.

Particle lifetime influencing viscosity could be possible. I'll keep this in mind when implementing #189

**Comment by k1ff** [comment]
Particle lifetime influencing viscosity will be a huge feature! Thanks so much!!!
