### ISSUE TITLE
[Feature Request] Add setting to emit inflow more than once per substep

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids-Beta#224]
**Problem**

At the moment, the simulator only emits inflow fluid at the start of a simulation substep*. This can cause a stuttering effect when using a fast moving object as an inflow.

*note: it has been found that there is a bug that causes fluid to only be emitted once per frame instead of at every substep.

**Solution**

Add a setting to the inflow object that allows the user to specify the number of times the inflow emits fluid during a simulation substep. Increasing the number will create a smoother and more continuous emission of fluid.

**Comment by Mitsuma** [comment]
Oh so this was actually a bug and/or missing feature?

![blender_2018-03-20_14-44-50](https://user-images.githubusercontent.com/8568089/37999532-95423c3e-3223-11e8-831d-931be39b3f0e.png)
![2018-03-20_14-47-05](https://user-images.githubusercontent.com/8568089/37999534-9648060e-3223-11e8-9308-75a187d1014a.png)
![2018-03-20_14-49-35](https://user-images.githubusercontent.com/8568089/37999535-97a2eec4-3223-11e8-9478-fe2704104a25.png)

Noticed that one time when I was playing around, increase of substeps did make it smoother. 
I thought thats just how it works based on the distance particles travel or so.

**Comment by rlguy** [comment]
This feature is only applicable to animated/keframed inflow objects. Here's an exaggerated example where an inflow cube moves across the domain very quickly over a few frames:

![untitled](https://user-images.githubusercontent.com/4285191/38004046-4e16b698-31ef-11e8-82ab-013fbcbc7bbe.jpg)

This causes a stuttering effect because fluid is only being emitted once per substep and the inflow object moves a lot in a single frame.

With the new 'Emission Substeps' parameter, the simulator will emit inflow fluid a specified number of times per substep to reduce the stuttering.

![untitled](https://user-images.githubusercontent.com/4285191/38004133-c0ce7ebe-31ef-11e8-87a2-d6196bf016f8.jpg)

Set to 2:

![untitled](https://user-images.githubusercontent.com/4285191/38004153-d69547f0-31ef-11e8-821f-c92e217fa6f5.jpg)

Set to 8:

![untitled](https://user-images.githubusercontent.com/4285191/38004199-fee4b07e-31ef-11e8-89dc-a5f2d57c54a4.jpg)

---

Anyways, this setting has been implemented! It will be included in the next version (**0.1.3b**) which should be available by March 31st.
