### ISSUE TITLE
[Feature Request] Air Incompressibility

### ISSUE THREAD

**Issue by RemiGraphics** [rlguy/Blender-FLIP-Fluids-Beta#228]
I know this request is a tad bit far-fetched, especially this early in development. But in the long run, I'd love to see something like this implemented.

Houdini released an update a while back with air incompressibility, so that air volumes are not compressed when fluid runs into a closed container.

Air incompressibility demo: https://vimeo.com/242284705

**Comment by rlguy** [comment]
Very cool feature, but I don't think this will be added in the near future! It would require quite a bit of change to the engine and I do not currently have the required knowledge for this type feature.

If in the future this becomes a possibility, I will reopen this issue!
