### ISSUE TITLE
[Test Case Results] nomadsoulx

### ISSUE THREAD

**Issue by nomadsoulx** [rlguy/Blender-FLIP-Fluids-Beta#229]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1861510/test_case_fluid_in_an_invisible_box100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1861511/test_case_fluid_in_an_invisible_box200.zip)
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1861512/test_case_fluid_in_an_invisible_box400.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1861545/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the tests ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
