### ISSUE TITLE
[Test Case Results] RevDr

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#23]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725044/test_case_fluid_in_an_invisible_box100.zip)

Will try a higher resolution next...

**Comment by rlguy** [comment]
Thanks RevDr!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by RevDr** [comment]
300 resolution test
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725693/test_case_fluid_in_an_invisible_box300.zip)

**Comment by RevDr** [comment]
400 resolution test
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1726731/test_case_fluid_in_an_invisible_box400.zip)
