### ISSUE TITLE
New Rapids with wetmaps

### ISSUE THREAD

**Issue by guitartom47** [rlguy/Blender-FLIP-Fluids-Beta#231]
Just my latest playing. 

https://www.youtube.com/watch?v=uCdCpu4DiBc

**Comment by rlguy** [comment]
Hey guitartom47, this looks great! Thanks for sharing.

I am wondering if you are aware of our [Facebook post](https://www.facebook.com/FLIPFluids/videos/1722175444515911/):

> Hey Beta Testers! We're looking for high quality animations to include in a demo video for the release of the FLIP Fluids Addon. If you would like your animation to be included in the demo, send us the video file to flip.fluids.beta [at] gmail.com and let us know how you would like to be credited. If your animation is chosen to be included in the demo, you will receive a discounted price (to be determined) upon the release of the addon.
>
> Requirements
> - Resolution: 1920x1080
> - Framerate: 30 frames per second
> - Deadline: April 18th 2018

If this is something you're interested in, send us the video file at flip.fluids.beta@gmail.com

**Comment by guitartom47** [comment]
oh good grief! Sorry to have posted this as an issue. :p I meant to put it in the shared art post and clicked in the wrong place. Thanks for the info though! I'll send a link to the video file when I can!!

**Comment by rlguy** [comment]
Thanks! No worries!
