### ISSUE TITLE
[Test Case Results] BlueHazmatMan

### ISSUE THREAD

**Issue by BlueHazmatMan** [rlguy/Blender-FLIP-Fluids-Beta#236]
Just ran the test at 125 resolution, there we no errors (as far as I know)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1873412/test_case_lighthouse125.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
