### ISSUE TITLE
[Test Case Results] origreg

### ISSUE THREAD

**Issue by origreg** [rlguy/Blender-FLIP-Fluids-Beta#237]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1873542/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by origreg** [comment]
Thanks so much!
