### ISSUE TITLE
[Test Case Results] perpetualcolor

### ISSUE THREAD

**Issue by PerpetualColor** [rlguy/Blender-FLIP-Fluids-Beta#238]
I ran cascading_water_feature-lite.blend at 100 resolution, and it displayed no errors. Here's the results:

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1873793/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
