### ISSUE TITLE
[Test Case Results] gopivfx

### ISSUE THREAD

**Issue by gopivfx** [rlguy/Blender-FLIP-Fluids-Beta#243]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1874428/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1874429/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1874430/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1874432/test_case_viscous_net65.zip)
Hi Rlguy, Did all test cases with 100 resolution and attached the results. During simulation, only 30-50% of my CPU  and 5 GB of RAM was used. Any ideas to utilize maximum resources...

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

Here's an explanation on resource usage: 
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal
