### ISSUE TITLE
[Test Case Results] CaseyWagner

### ISSUE THREAD

**Issue by CaseyWagner** [rlguy/Blender-FLIP-Fluids-Beta#244]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1875659/test_case_cascading_water_feature100.zip)

Test case ran to completion. Attempting a render resulted in a crash on the 8th frame, but unfortunately Blender did not generate a crash log for this attempt.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
