### ISSUE TITLE
[Test Case Results] ErkBlender

### ISSUE THREAD

**Issue by ErkBlender** [rlguy/Blender-FLIP-Fluids-Beta#245]
The baking was a lot faster than the default Blender fluid system, which I was very happily surprised about.
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1875787/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks, glad you're enjoying it!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
