### ISSUE TITLE
[Test Case Results] PavelBlend

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids-Beta#246]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1876550/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by rlguy** [comment]
This sounds like a bug, that was message should have changed to ‘safe to quit blender’ and the sim should have stopped.

It should be okay to quit Blender. There is a very small chance it may corrupt your cache.

I’ll be able to look into this further on Monday.

**Comment by PavelBlend** [comment]
I restarted the blender.
Statistics appeared for all baked frames.
And the cache was not damaged.
