### ISSUE TITLE
No documentation for parameters

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids-Beta#252]
The following parameters are missing in the documentation:
Inflow Object Settings > **Rigid, Deformable** (Add Object Velocity to Inflow)
Domain Surface Settings > **Mesh Around Obstacles**

**Comment by rlguy** [comment]
Thanks for letting me know! This has been added:
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Inflow-Object-Settings
