### ISSUE TITLE
[Test Case Results] teller2010

### ISSUE THREAD

**Issue by teller2010** [rlguy/Blender-FLIP-Fluids-Beta#253]
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1880435/test_case_cascading_water_feature400.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by rlguy** [comment]
Thanks! These high resolution test will help us a lot!
