### ISSUE TITLE
[Test Case Results] exwnest

### ISSUE THREAD

**Issue by exwnest** [rlguy/Blender-FLIP-Fluids-Beta#256]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1884524/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1884525/test_case_cascading_water_feature200.zip)
[test_case_cascading_water_feature300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1884526/test_case_cascading_water_feature300.zip)
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1884528/test_case_cascading_water_feature400.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the tests ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
