### ISSUE TITLE
[Test Case Results] CultOfApe

### ISSUE THREAD

**Issue by CultOfApe** [rlguy/Blender-FLIP-Fluids-Beta#258]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1885841/test_case_cascading_water_feature100.zip)
Just a quick test to make sure installation working properly on my system, will run higher res tests tomorrow.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors and working properly on your system.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
