### ISSUE TITLE
[Test Case Results]FERNANBOP

### ISSUE THREAD

**Issue by FERNANBOP** [rlguy/Blender-FLIP-Fluids-Beta#26]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725329/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725330/test_case_cascading_water_feature200.zip)
![test_case_cascading_water_feature200_error01](https://user-images.githubusercontent.com/26856194/36223226-077f48d0-11c4-11e8-8d6b-376c0f18604c.jpg)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725331/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725332/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725333/test_case_viscous_net65.zip)

These are the test cases I have done at the moment. The jpg image is a screenshot of the error I got while I was baking the 2nd test, but I hit the "resume" button and it finished succesfully. Maybe I will make some more with higher resolutions tonight, when I can leave the computer baking a few hours, while I sleep :) 
I hope this is helpfull. Let me know what else I can do for you. I really like your software. Thank you for this chance.

Fernando Montero

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the tests ran fine. Submitting test cases is very helpful and will help us improve the addon! I'll look into this error.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by FERNANBOP** [comment]
I've done three more tests:
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732570/test_case_cascading_water_feature400.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732571/test_case_fluid_in_an_invisible_box200.zip)
[test_case_viscous_net150.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732572/test_case_viscous_net150.zip)
I'll try to free some hard drive space so I can do a couple more.
Meanwhile, I am making my own experiments with the addon, and I'm really enjoying it, but I have a question: Is it possible to change the inflow color along time, or mixing two diferent color inflows?

**Comment by rlguy** [comment]
Thanks for the test results!

It is not possible at the moment to mix different colors. Details about this in this issue: #48
