### ISSUE TITLE
[Test Case Results] 	IIBit

### ISSUE THREAD

**Issue by IIBit** [rlguy/Blender-FLIP-Fluids-Beta#260]
Hey, I ran the lighthouse.blend test case at 125 resolution and I think it ran okay. Here are the results:

[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1886305/test_case_lighthouse125.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Your Dropbox folder should contain a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
