### ISSUE TITLE
[Feature Request] Simulating Honey Coiling

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids-Beta#261]
Is it possible to implement such an effect (right)?:
https://youtu.be/QJePco0_os8?t=46
Or as here:
https://youtu.be/ZEjUqZU1hNQ?t=51
That the viscous liquid is twisted along the ring.
I have not yet managed to achieve this effect

**Comment by rlguy** [comment]
I have seen those videos and looked over the paper! In this simulator, we use the 'decoupled' simulation technique, so the type of coiling you see with honey would be difficult to achieve.

Unfortunately we likely won't be implementing this viscosity method in the near future. This would involve a large rewrite of the solver code and I do not have the knowledge to make these kind of changes yet. The coiling viscosity method, due the the accuracy, also takes quite a bit more time to simulate. If in the future this feature becomes more possible, I will reopen this issue.
