### ISSUE TITLE
[Feature Request] Particle Outflow/Killer

### ISSUE THREAD

**Issue by RemiGraphics** [rlguy/Blender-FLIP-Fluids-Beta#265]
Using this add-on, I'm currently working on replicating realistic curling waves in Blender. It's been a really fun project so far, but there's one thing I'm struggling with in regards to whitewater generation.

--

![image](https://user-images.githubusercontent.com/37308267/38464334-c68b1e44-3ad1-11e8-8cc5-d1a02fbc973d.png)

This is my apparatus for creating these waves. The "pusher" object oscillates up and down creating the waves. The issue is, when it falls, it creates a small pocket of air. This pocket ends up generating tons of bubble particles which lead to an excessive about of foam sitting above the pusher. See the right side of the simulation below.

https://www.youtube.com/watch?v=tvTv3lASevk

I'd love to see some workaround for getting rid of these extra particles, whether that be adding some sort of particle outflow, or implementing it with Blender's existing collision objects physics to allow for particle killing.

Again, great job with this add-on. It's really impressive to see what you've done so far! 
Cheers.

**Comment by RemiGraphics** [comment]
Oh! I didn't know outflows could be configured like that. That solves my issue.

Thanks for the tip! I figured it might do something like that, but I was too lazy to test it myself.

**Comment by rlguy** [comment]
No problem, glad it was an easy issue to solve!
