### ISSUE TITLE
animated parameter names do not show up in dopesheet

### ISSUE THREAD

**Issue by FlipFloh** [rlguy/Blender-FLIP-Fluids-Beta#266]
when animating "viscosity" or "boundary friction" for example, dopesheet shows ( ) instead of the names.

**Comment by rlguy** [comment]
Thanks for letting me know about this! Turns out there were quite a few parameters that had missing or incorrect names, which is why they weren't showing up in the dopesheet. These have been fixed and will be included in the next version (**0.1.4b**).
