### ISSUE TITLE
Nothing baking when using "Inverse"

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#267]
Just have a very basic setup, a domain, a collision and a fluid inflow.

![capture](https://user-images.githubusercontent.com/36161534/38486573-b9c84d50-3bdd-11e8-8517-45c1225cac31.PNG)

When I click the "inverse" option on the collision object, no fluid appears when baking. But when it's unchecked, the fluid is visible. Not sure why it's not showing up.. Am I missing something?

**Comment by rlguy** [comment]
Hey, here’s an explanation in this issue: #69
