### ISSUE TITLE
[Test Case Results] left_coaster

### ISSUE THREAD

**Issue by left-coaster** [rlguy/Blender-FLIP-Fluids-Beta#27]
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725434/test_case_cascading_water_feature200.zip)

**Comment by rlguy** [comment]
Thanks left-coaster!

I checked your results and it looks like the test ran okay, but you are affected by issue #7.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue and also your other test case thread (#16). Please post any further test case results to this thread.

**Comment by left-coaster** [comment]
I can try disabling the intel gfx device so that only the nvidia is visible
to blender....maybe.
