### ISSUE TITLE
Domain Open Boundary 

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#270]
Is it possible to make the domains boundary open so that the fluid doesn't collide with it but rather just keeps on it's trajectory?

**Comment by rlguy** [comment]
This is not possible with this type of simulation method (FLIP). The FLIP method relies on a grid to track simulation data and that is why a domain boundary is required. Fluid calculations cannot be made outside of the domain grid. A different simulation method that is not grid-based, such as SPH, could do this.

If an adaptive domain feature (#268) is implemented, the domain could grow to allow fluid to keep moving outwards. But if the domain becomes too large, the simulation will quickly slow down and may run out of memory.
