### ISSUE TITLE
Up resing simulation issue

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids-Beta#272]
Hi there,

I have a simulation where I have something drop into a tank of water. I've been working at a simulation resolution of 100 and crafted the splash until I liked the low resolution simulation. Then I bumped it up to a resolution of 200 to see what it would look like with a little bit more resolution and after waiting for quite a while, no splash. The collision object just falls through the fluid and the surface doesn't react at all, but at a lower resolution I am getting a splash. Just wondering what is happening here..

**Comment by rlguy** [comment]
Sounds odd! Would you be able to upload the .blend file, or send it to flip.fluids.beta[at]gmail.com?

**Comment by RevDr** [comment]
I seem to get the opposite - had a low resolution sim (100) I was happy with of an object coming out of water.  Set it to 300 and the 'splash' is significantly bigger.

**Comment by k1ff** [comment]
I have mailed the blend file to you Ryan. Maybe I did something wrong.. But couldn't for the life of me get a result at higher resolutions

**Comment by RevDr** [comment]
Here are a couple of images.... only difference in sim is the resolution,
![splashdiff1](https://user-images.githubusercontent.com/36420510/38798187-c4dd85b8-4158-11e8-9856-e57489d953e9.PNG)
![splashdiff2](https://user-images.githubusercontent.com/36420510/38798191-c7a85dd6-4158-11e8-908b-ac788b4b5908.PNG)

**Comment by rlguy** [comment]
Hey k1ff,

Thanks for the .blend file, I checked it out!

It looks like your obstacle object is moving too fast for the simulator to resolve at that resolution. At 200 resolution, the object is moving about 96 grid cells in a single frame. You have _**Enable Adaptive Time Stepping for Obstacles**_ enabled, so this is good. This will take into account obstacle speeds when calculating substeps. By default, fluid/obstacles are only allowed to move 5 grid cells in a single substep (_Safety Factor Setting_) to keep the simulation stable and accurate. 

With _**Max Substeps**_ set to 8, the simulator will only be able to resolve obstacle objects accurately moving less than **_8 x 5 = 40_** grid cells per frame. For an obstacle moving 96 grid cells in a frame, you would need the Max Substeps value set to 20 or more for an accurate simulation. This is quite high and I would not suggest allowing the simulator to take this many substeps. This will result in quite a long baking process. Taking this many substeps can also lead to simulation errors. The simulator only sees the obstacle as snapshots at each frame and has to make guesses about the state of the obstacle at substeps between frames. I would instead suggest slowing down the obstacle so it does not move as far in a single frame. If you want an obstacle moving this fast, I would suggest increasing the framerate as if you are simulating in slow motion and then speeding up the animation when rendering.

Hope this helps!
