### ISSUE TITLE
Multiple Inflows BUG

### ISSUE THREAD

**Issue by DVFXAustralia** [rlguy/Blender-FLIP-Fluids-Beta#273]
When ever I tried to create 4 inflows inside the Domain ( by copying and pasting the first  Inflow object ), the last inflow object created as an instance of the first  inflow object ( by pasting ) acts different from other 3 inflow objects even after having same settings.
I faced this issue 2 times. Both times, I deleted the fourth inflow and pasted again /or/ created a same new object to act as an inflow, then it worked right /or/ removed the FLIP Fluid and reapplied the FLIP Fluids to the same object .

![inflow bug](https://user-images.githubusercontent.com/18499083/38768193-062e83f4-4033-11e8-9246-8a209b675ce4.jpg)

In the picture above, you can see that the 3 inflow objects are behaving in a similar fashion, but the last inflow object is acting differently even after having same exact settings.

**Comment by rlguy** [comment]
Thanks for reporting this! Would you be able to upload the .blend file, or send it to flip.fluids.beta[at]gmail.com for me to test?

**Comment by rlguy** [comment]
Thanks for the update! I’ll keep an eye out for this too and close this issue until there is more info on how to repeat it.
