### ISSUE TITLE
OSError: Access Violation

### ISSUE THREAD

**Issue by TekCastPork** [rlguy/Blender-FLIP-Fluids-Beta#274]
So today I made a new scene where some fluid will pour out of a container into a cup, but after the plugin exports the keyframe data (since the container moves) it begins to start the simulation but errors with:

OSError: exception: access violation reading 0x0000000000000035
before computing the first frame.

All other scenes I've made have worked perfectly so it may be something to do with this scene, like how the container and cup were modelled in Fusion 360 beforehand (because I suck with sculpt mode still 😛) but I thought I'd report it anyway since access violations generally are never wanted. 

Console Window output is linked here (an actual log file is never generated as far as I can find): [Output Window](https://pastebin.com/QzX1c9vP)

Here is the .blend file and such: [Blend File](https://drive.google.com/open?id=1YtoRQfGIMAxvrCqcGA2H4N9slx2zzUPv)

**Comment by TekCastPork** [comment]
Ok after a little bit of testing it seems to have something to do with the Container (vase looking thingy if you open the blend) that I modelled in Fusion, not the cup. I'm going to try a re-export from Fusion of the model, since I used a custom setting that uses a lot of triangles, and update when I have results.

**Comment by TekCastPork** [comment]
UPDATE: I lowered the quality settings of the STL file output from Fusion from my custom one to Medium and it now will simulate. Probably had something to do with the giant amount of triangles the original STL had and the plugin not being able to handle them.

**Comment by rlguy** [comment]
Thanks for uploading the .blend file, I checked this out!

It looks like the container is too detailed for the plugin to handle. At over 300K faces the exported animation is about 1.8GB. It would be best to use a less detailed model for simulation and use the detailed model for rendering. The simulator does not require that much mesh detail and will bake faster for models with lower face counts.
