### ISSUE TITLE
This cup leaks - which setting do I need to change?

### ISSUE THREAD

**Issue by ShadowMakerSdR** [rlguy/Blender-FLIP-Fluids-Beta#279]
Hi,

I was trying to fill up a cup and then tip it over, but for some reason there are some drops leaking through the cup. I've tried changing the friction and expand values of the cup, but it didn't seem to make that much of a difference. I've upped the timesteps to go from minimum 1 to maximum 40, but it sill leaks. So what do I need to change to prevent this from happening?

[008_zelfgemaakte_beker.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1934373/008_zelfgemaakte_beker.zip)

![008_tipping_cup](https://user-images.githubusercontent.com/36409000/39083020-37b53eb6-455d-11e8-8e7e-0bfa8ec6c1ee.gif)

**Comment by rlguy** [comment]
Hey ShadowMakerSdR,

I'm not at a computer where I can test this scene right now. I'll be able to test after the weekend if needed.

You may want to check out these tips:
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/148#issuecomment-368624558

Number 3 may be a good solution for this type of simulation:
>3. **If possible, use a thick object for simulation and the thin object for rendering** - This depends on what kind of animation you are trying to achieve

For the timesteps, if you want to force more timesteps to be taken, you will need to increase the minimum value. Forcing the simulator to take more timesteps will cause the fluid to move less distance and could help prevent fluid particles slipping through the obstacle.

Hope this helps!

**Comment by Mitsuma** [comment]
Actually I think the problem is of a different nature and way simple. 

![blender_2018-04-22_04-59-30](https://user-images.githubusercontent.com/8568089/39090899-103d5020-45ea-11e8-953a-51368e582a33.png)
![blender_2018-04-22_05-01-23](https://user-images.githubusercontent.com/8568089/39090912-453d4ea6-45ea-11e8-8622-3b337eedc31b.png)

Your cup leaks because it has an actual hole in the mesh.

**Comment by ShadowMakerSdR** [comment]
> > Quick note, what you uploaded is actually not the same scene as your gif.
> The zip file is the same cup but has a viscous fluid.

It does? That's not what I used to run the simulation.
I did flip back and forth through the presets, but I didn't 'add them to stack' or 'applied' them.
So just looking at the presets by cycling through them, changes the values of the simulation.
Wow. I don't know about the rest of you, but that's unwanted behavior as far as I'm concerned.
If you have the options to make 'stacks' or 'apply settings' they shouldn't apply by themselves. One inadvertent click will then mess up carefully crafted settings. At the very least this should be documented behavior.

> Your cup leaks because it has an actual hole in the mesh.

Okay, I feel stupid now. I spent a lot of time making the cup with a screw modifier and I thought I had checked it. I'll try again with a closed cup. If this indeed solves it, my apologies to @rlguy for wasting his time to follow up on this.

Thank you @Mitsuma

**Comment by rlguy** [comment]
> Okay, I feel stupid now. I spent a lot of time making the cup with a screw modifier and I thought I had checked it. I'll try again with a closed cup. If this indeed solves it, my apologies to @rlguy for wasting his time to follow up on this.

No worries! I'm glad it ended up being an easy fix. No time wasted.

Thanks for looking into this, @Mitsuma!
