### ISSUE TITLE
Fluid not showing in render or 3D viewer

### ISSUE THREAD

**Issue by TekCastPork** [rlguy/Blender-FLIP-Fluids-Beta#282]
I planned to make a new simulation today but the fluid surface does not show up in the viewport or in renders.

The plugin is making the files in the cache, though, so it's not a problem of the files not being generated.

Even stranger, I can go to previous simulations and re-bake them and the problem persists as well.

Things I've tried:

Reinstalling Blender (even deleting the AppData that uninstalling doesn't)
Reinstalling the plugin completely
The ray visibility settings are checked and the "include in render" camera is clicked so it will be rendered, but it still does not show.

Even starting a brand new file and having a domain cube and fluid cube, it will bake but not show.

Suggestions?

**Comment by rlguy** [comment]
See #284
