### ISSUE TITLE
Simulation runs without creating/showing mesh, and test files are failing

### ISSUE THREAD

**Issue by TheDuckCow** [rlguy/Blender-FLIP-Fluids-Beta#285]
Hello,

I previously downloaded the addon and ran some simple, self-made tests in blender without issue. Simulations ran fine, no issues. Today I have come back, and now it is not working.

**Some details about my situation:**
- When pressing simulate, it appears to be working.. but then the display mesh is not actually showing up, ie the water does not actually display. It is not hidden or on some other layer (all layers enabled, pressed alt-h just to be safe not hidden). 
- I have tried completely removing the addon, restarting blender, and re-installing it without resolving the issue
- I have tried opening previous simulations I ran (they would appear fine, I could even play back old simulation cache data), however when pressing Bake again on those files, the simulation data would of course be reset and the issue would occur again (you can see that below in the first video around

Full demo video of what I am experiencing here; and again, it was previously working on the same system and the same version of blender, so unsure why this is occuring now. 
https://drive.google.com/file/d/1B1opJrZ6WE_94XT1exNN5azQFjNymEg7/view?usp=sharing

In a similar but separate fashion, please also see this video of my attempt to now run one of the test examples (which is failing even before baking):
https://drive.google.com/file/d/1rv2gjE5P__EqUt5JiAao78LROPLsEpRU/view?usp=sharing

Happy to attempt to debug further. 
Flip addon version: 0.1.3
GPU device list detected by addon (which is accurate): GeForce GTX TITAN (1)

**Comment by rlguy** [comment]
See #284
