### ISSUE TITLE
Fluid InFlow directional?

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids-Beta#287]
With Blender Fluid, I can use a flat plane and use its directional to control fluid, how does FLIP fluid does it? So far, I did manage to inflow some fluid from 3D objects, but flat mesh and directional is not in the option?

I would like to control the FLIP fluid with the direction of my mesh, is this possible?

**Comment by enzyme69** [comment]
I can see there is this Inflow "Target" option, which can sort of direct the velocity into target object, but it is not as immediate as "Shell and Direction". Is this a future feature?

**Comment by rlguy** [comment]
For inflow, outflow, and obstacle objects there is a requirement that the mesh has a volume. The mesh must be [Manifold](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Manifold-Meshes). Perhaps in the future, we may be able to select a face of the mesh to use as a direction. For now, you should use 3D objects with a target. I usually just set an empty object as a child to the inflow.
