### ISSUE TITLE
Keyframed Animation for Fluid or can it be "LIVE"?

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids-Beta#288]
Is it possible for FLIP fluid simulation to accept some kind of "LIVE" or non keyed animation and react to it? Such as if we have playback running, but would like it to update as I move obstace?

I am also using procedural nodes a lot like Animation Nodes, would be nice to be able to run simulation with live nodes, without baking. Is this possible?

**Comment by rlguy** [comment]
This is not possible in this addon. All meshes must be exported before the simulation begins baking.
