### ISSUE TITLE
Somewhat the first part of simulations not showing...

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids-Beta#289]
This must be a bug. I have many simulations where the first 100-300 frames or more, basically beginning part is not showing anything, until later.

What I did was deleting cache and resimulating many times. And somewhat this happens quite often.

**Comment by rlguy** [comment]
Hey enzyme69,

I am wondering about a few things:  
- Which addon version you are using?
- Does disabling GPU features in the [Advanced Panel](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings) solve this issue?
- Would you be able to attach a .blend file where this is happening?

**Comment by enzyme69** [comment]
- I am using version 1.0.0.
- Disabling GPU? Will CPU and GPU give different result

Well with the missing frames at the beginning, it seems to be fixed if I enable "Force" bake. Instead of "Default".

The Blend is very specific for this secret project. 

But will try simpler one. 

Anyhow, first part of sim "not showing" is probably a bug where it skips, because I hit reset and resims too fast.
