### ISSUE TITLE
[Test Case Results] fwidman

### ISSUE THREAD

**Issue by fwidman** [rlguy/Blender-FLIP-Fluids-Beta#29]
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725447/test_case_lighthouse125.zip)

I could not see that any of my two GPUs was utilized.
But everything seemed to run smoothly.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran okay, but you are affected by issue #7. There is also some discussion in that issue about low GPU usage.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
