### ISSUE TITLE
[Test Case Results] simplesolo

### ISSUE THREAD

**Issue by simplesolo** [rlguy/Blender-FLIP-Fluids-Beta#30]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725470/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725471/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725472/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725473/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks simplesolo!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by simplesolo** [comment]
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746357/test_case_cascading_water_feature400.zip)
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746358/test_case_fluid_in_an_invisible_box400.zip)
[test_case_lighthouse500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746359/test_case_lighthouse500.zip)
[test_case_viscous_net200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746360/test_case_viscous_net200.zip)
