### ISSUE TITLE
[Test Case Results] niklassjogren

### ISSUE THREAD

**Issue by niklassjogren** [rlguy/Blender-FLIP-Fluids-Beta#32]
Hi. Did some of the tests, mostly low resolution, on my desktop computer and I think without any problems! I'll try to do some more of those with higher resolution during the evening!

**Desktop** computer results:
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725475/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725476/test_case_viscous_net65.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725477/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725478/test_case_fluid_in_an_invisible_box100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725479/test_case_fluid_in_an_invisible_box200.zip)

You also got details on my laptop, when I run the tests on that machine should I just put the exported "results" here in the same thread too?

/Niklas

**Comment by rlguy** [comment]
Thanks niklassjogren!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread. Test cases run on other machines can be put here too.

**Comment by niklassjogren** [comment]
Here are some results from my other computer!

**Laptop** Result:
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1727067/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1727068/test_case_viscous_net65.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1727069/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1727070/test_case_fluid_in_an_invisible_box100.zip)

/Niklas
