### ISSUE TITLE
[Test Case Results] EODEFX

### ISSUE THREAD

**Issue by EODEFX** [rlguy/Blender-FLIP-Fluids-Beta#33]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725573/test_case_fluid_in_an_invisible_box100.zip)
Was able to get it up and running and blazed through the first test. I'm loving how it looks.

**Comment by rlguy** [comment]
Thanks EODEFX!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
