### ISSUE TITLE
[Test Case Results] HEEROCKSS

### ISSUE THREAD

**Issue by HEEROCKSS** [rlguy/Blender-FLIP-Fluids-Beta#35]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725691/test_case_cascading_water_feature100.zip)

Im busy at the moment so could only do a short test but worked at first try, pretty impressive!

**Comment by rlguy** [comment]
Thanks HEEROCKSS!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by rlguy** [comment]
> HEEROCKSS:
>
> [test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732172/test_case_cascading_water_feature400.zip)
A Test with my 72 Cores Server, worked perfectly fine but it took longer than my overclocked 3930k. Seems Simulations scale better with fast single core performance than lots of cores.

The simulator and FLIP simulation method has some bottlenecks where sections of code are single-threaded, so this is why faster single core performance was faster. I took a look at the logs, and it looks like the simulator was running with 36 threads. This may be too many threads for the simulator to run efficiently. In the beta version of the addon, I would suggest trying 12 or 16 threads (Set in the _FLIP Fluid Advanced_ panel) to see if that improves performance.

A planned feature for the future is to have the addon generate meshes post-simulation. This could provide a massive boost for systems like yours with many threads. It would be possible to mesh multiple frames simultaneously. At the moment, meshing is done frame-by-frame and often accounts for half of the simulation time.
