### ISSUE TITLE
[Test Case Results] xepher313

### ISSUE THREAD

**Issue by Xepher313** [rlguy/Blender-FLIP-Fluids-Beta#36]
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725716/test_case_cascading_water_feature200.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725717/test_case_fluid_in_an_invisible_box100.zip)

Didn't really have time to do a big one, but uh, oh well. Seems pretty good so far!

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
