### ISSUE TITLE
[Test Case Results] Retrific

### ISSUE THREAD

**Issue by Retrific** [rlguy/Blender-FLIP-Fluids-Beta#37]
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1725930/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks Retrific!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
