### ISSUE TITLE
[Test Case Results] EverSimo

### ISSUE THREAD

**Issue by EverSimo** [rlguy/Blender-FLIP-Fluids-Beta#38]
I run the cascading water test scene here at 100 and 200 resolution and it finished successfully.
I'm running the same scene at 300 resolution now to see how it goes.
My processor is only a few seconds behind the original processor that appears in the tooltip from the resolution button.

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1726052/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1726053/test_case_cascading_water_feature200.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by EverSimo** [comment]
In this specific scene, I faced some crashes related to rendering... sometimes blender just closes.
Now I'm testing the actual complete build of the addon.

[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1729969/test_case_fluid_in_an_invisible_box300.zip)

**Comment by rlguy** [comment]
Hey EverSimo,

There is some discussion of render crashes in this issue: #34.

**Comment by EverSimo** [comment]
Hi, rlguy... some random questions:
Is there a plan to support Linux Ubuntu?
Is there a plan to integrate the blender force fields and rigid bodies?
Is there a plan to mix different viscosities in the domain? Like, choose the viscosity in the fluid object settings instead of a global option? So I can have one fluid objects as water and other as honey, or milk and chocolate?

**Comment by EverSimo** [comment]
I forgot to ask about motion blur... Is there a way to use the cycles native motion blur?
Also, if I want to use the spray particles to emit smoke to simulate the thinner spray like a vapour, they store some kind of motion? Speed Vectors?

**Comment by rlguy** [comment]
Not at the moment, unfortunately. As of now, we are not able to export velocity data via an addon into Blender so that it can render with motion blur, or use velocity data for whitewater particles. We are investigating if we may be able to do this in the future by exporting data to an Alembic cache, but we may need help from the Blender developers to get this working within Blender.

**Comment by EverSimo** [comment]
I'm not sure if there's a thread to show videos and images from tests results.
[Beach Render(Unfinished)](https://r4---sn-q4flrner.googlevideo.com/videoplayback?id=2aef60ac7caf24eb&itag=37&source=picasa&begin=0&requiressl=yes&pl=23&sc=yes&ei=QjWPWs-wH9Cz-wWL76K4Ag&susc=ph&app=fife&mime=video/mp4&cnr=14&lmt=1519330605857962&ip=170.84.59.140&ipbits=8&expire=1519341922&sparams=app,cnr,ei,expire,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,sc,source,susc&signature=4B5ECFC619220342EEA3F564E194F27A2DDEDE36.6CF328D07A7B2EECDE293C925FE36428217F24C2&key=cms1&redirect_counter=1&cm2rm=sn-bg0lk7z&req_id=dcbe6d0142cca3ee&cms_redirect=yes&mm=34&mn=sn-q4flrner&ms=ltu&mt=1519334557&mv=m)

[Beach Vieport full length simulation](https://r6---sn-bg07dney.googlevideo.com/videoplayback?id=75ce6177d1094c25&itag=37&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-bg07dney&ms=nxu&mv=m&pl=23&sc=yes&ei=NTePWvzwAczy-gWWnIzoBQ&susc=ph&app=fife&mime=video/mp4&cnr=14&lmt=1519330551373145&mt=1519335202&ip=170.84.59.140&ipbits=8&expire=1519342421&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,sc,ei,susc,app,mime,cnr,lmt&signature=7884CEE72C98DC9C97617991F35D8BC28BC31D5B.04693F3D87070CE2A17B0F6E3C56374774A88A74&key=ck2)

**Comment by rlguy** [comment]
Cool! It would be great to get that banding issue fixed to improve this scene! I have opened this thread for posting animations: #116
