### ISSUE TITLE
[Test Case Results] petitwilly

### ISSUE THREAD

**Issue by petitwilly** [rlguy/Blender-FLIP-Fluids-Beta#40]
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1727268/test_case_cascading_water_feature400.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1727269/test_case_cascading_water_feature100.zip)

Test OK !
All is good for me.

**Comment by rlguy** [comment]
Thanks petitwilly!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
