### ISSUE TITLE
Apply changes to domain transform doesn't work properly

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#41]
Hi,

If I translate/rotate the domain origin and then apply the transform (Ctrl A -> then choose rotation or translate) those changes are not reflected properly in FLIP Fluid sim.

Thanks

**Comment by RevDr** [comment]
For example I have translate and rotated domain (note also you can't see that rotation) and then applied transform and rotation/scale.

As you can see it is not working.  My fluid to left of the domain should not have been generated at all.

Thanks

![bug3](https://user-images.githubusercontent.com/36420510/36253311-0f0ae7be-123f-11e8-9712-0bcc45344735.JPG)

**Comment by rlguy** [comment]
I have fixed some bugs regarding the fluid meshes not following the domain transforms properly. These fixes will be included in the next addon version (0.1.2b).

Some notes:
- The domain should be aligned to the x/y/z axis' before baking. If the domain is rotated, the simulator will take the axis aligned bounding box of the rotated domain object and use that shape for the simulation.
- If you apply a scale/location transform to the domain and the loaded meshes aren't in the correct location, you should delete the surface/whitewater mesh objects and reload the frame. As far as I know, there is not a simple way to tell when a transform has been applied to an object with the Python API, so the mesh objects won't be updated with the applied transform.

**Comment by RevDr** [comment]
OK – fab.
