### ISSUE TITLE
Render in viewport not working

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids-Beta#44]
Hi,

The title says it all really.

Just get a rendered cube for the domain when rendering in the viewport.

Thanks

**Comment by RevDr** [comment]
My mistake.

I had left visibility on for the domain.  <blush>

**Comment by rlguy** [comment]
When rendering in the viewport, you'll need to uncheck the _restrict viewport visibility_ eye icon in the outliner to exclude it from rendering. This can be annoying if you have both a rendered viewport and normal viewport open and still want to have the objects visible in the normal viewport while being excluded from rendering in the rendered viewport.

The addon will now exclude domain, fluid, inflow, and outflow objects from rendering in Cycles by automatically disabling their Cycles _ray visibility_ settings. These changes will be included in the next addon version (0.1.2b)

![cycles_visibility_settings](https://user-images.githubusercontent.com/4285191/36280524-61418dde-124f-11e8-9ac2-85334043f93a.jpg)
