### ISSUE TITLE
Changing Preview Resolution doesn't change anything

### ISSUE THREAD

**Issue by Retrific** [rlguy/Blender-FLIP-Fluids-Beta#46]
Changing this option does not have any influence on how the fluid is displayed.
![image](https://user-images.githubusercontent.com/8227911/36262117-d0682b84-1266-11e8-90e7-6268aa337d7d.png)

Only when I switch to Final here I can see how the high res fluid actually looks
![image](https://user-images.githubusercontent.com/8227911/36262154-e2cab440-1266-11e8-90c3-4111bf51c3c7.png)

**Comment by GCharb** [comment]
You need to set the values before you bake, the way I see it is that it generates two sets of surface, one for the viewport, using the preview value, and one for render, using the final value!

**Comment by rlguy** [comment]
That is correct ^^

Many of the domain settings must be set before baking to take effect. I have opened issue #50 to add documentation for which settings these are.
