### ISSUE TITLE
Icon to display preset info on UI

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#49]
An icon to display a preset info is now "question" mark.
This is my opinion. I think that it is not good, because I think that it is for showing some help.
I think that it is better the icon is showing " ! " mark as blender info editor's icon.

![figure](https://user-images.githubusercontent.com/36343687/36278392-1397216a-12d7-11e8-97af-5b146114f2ac.jpg)

**Comment by rlguy** [comment]
Good suggestion, and this makes sense! I have changed the icon and this improvement will be included in the next beta addon version (0.1.2b).
