### ISSUE TITLE
[Test Case Results] Dekker3D

### ISSUE THREAD

**Issue by Dekker3D** [rlguy/Blender-FLIP-Fluids-Beta#51]
The test case proceeded more slowly than I'd hoped, but with no issues as far as I could tell. The viscous net scene was my favourite of the shown scenes, so of course I had to have a go at it.

[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1729504/test_case_viscous_net65.zip)

**Comment by rlguy** [comment]
Thanks Dekker3D!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
