### ISSUE TITLE
[Test Case Results] gordeaoux

### ISSUE THREAD

**Issue by gordeaoux** [rlguy/Blender-FLIP-Fluids-Beta#52]
Hey, I ran the cascading_water_feature.blend test case at 100 resolution and I think it ran okay. Here are the results:

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1729669/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
