### ISSUE TITLE
Simulation ignores Path Animation?

### ISSUE THREAD

**Issue by Retrific** [rlguy/Blender-FLIP-Fluids-Beta#53]
I have a sphere (inflow) following a path but when simulating the inflow only comes from the spot where the sphere was when I hit bake. The Inflow in the simulation does not follow the animated object.

![image](https://user-images.githubusercontent.com/8227911/36288285-3371e6fe-12ba-11e8-946f-783d7da028ed.png)

**Comment by rlguy** [comment]
Hey Retrific,

Is the 'Export Animated Mesh' option checked on the inflow object? This option must be checked for animated objects. Objects that have keyframed location/rotation/scale do not need this option checked.

**Comment by Retrific** [comment]
Oh i thought this was only for when the mesh itself is animated, as in shape keys or armatures

**Comment by rlguy** [comment]
No problem! Any animation more complicated than keyframed loc/rot/scale will need to have the _Export Animated Mesh_ option checked.
