### ISSUE TITLE
[Test Case Results] gimble3d

### ISSUE THREAD

**Issue by gimble3d** [rlguy/Blender-FLIP-Fluids-Beta#54]
Hi Ryan

I've completed running the fluid_in_an_invisible_box.blend fluid simulation
at the 100/200/300/400 resolutions. Here's the results:

[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730050/test_case_fluid_in_an_invisible_box100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730051/test_case_fluid_in_an_invisible_box200.zip)
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730053/test_case_fluid_in_an_invisible_box300.zip)
[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730054/test_case_fluid_in_an_invisible_box400.zip)

I'm a little surprised that my bake times were significantly longer than the
ones posted at the 'Test Suite Scenes' page. My times, versus the posted times
for the 100/200/300/400 resolutions were 1.64/1.45/1.29/1.26 times longer.
I was careful not to run any other programs while the bakes were being performed.
(Other than a couple file explorers and Resource monitor).

Is there a page where I can compare my bake times to people with a similar computer
system?

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

> Is there a page where I can compare my bake times to people with a similar computer
system?

I will be compiling a chart of timing data for many hardware setups once enough test results are collected.

There is another tester with the same CPU, but a GTX 970. The timing results are a bit surprising. The other tester's results are significantly quicker. I checked the timing results spent on GPU calculations and your GTX Titan timing is nearly the same as the GTX 970.

Here are the results in seconds:

| | 100 | 300 | 400 |
| -- | -- | -- | -- |
| gimble3d | 870.248 | 14063.2 | 34223.1 |
5820K @ 3.30GHz, GTX 970, 64GB RAM | 647.784 | 11318.6  | 28378.6 |

**Comment by gimble3d** [comment]
That's interesting.

Which version of windows are they using?

I've tried a few things, but the results only improved marginally:
(Using fluid_in_an_invisible_box.blend at 100 resolution - original bake time 14:45)

- updated bios for motherboard (ASUS X-99A) to version 3801
bake time: 13.04

- moved blend file from hard drive to SSD
bake time: 13:28

- updated video card driver to version 390.77
bake time: 13:30

I'm not sure what else I can try hardware wise.
I'm running at stock speeds (no over clocking).
Using DDR4 PC4-17000 2133 MHz RAM, which according to:
https://ark.intel.com/products/82932/Intel-Core-i7-5820K-Processor-15M-Cache-up-to-3_60-GHz
is the fastest RAM supported by the 5820k.

I did have some issues initially running the Cycles benchmarks using the TitanX GPU at:

https://code.blender.org/2016/02/new-cycles-benchmark/#comment-66100
https://code.blender.org/2016/02/new-cycles-benchmark/#comment-69536
https://code.blender.org/2016/02/new-cycles-benchmark/#comment-71206

but it seemed the issues were eventually "straightened out" after blender and GPU driver updates.


Here's my bake results for

Cascading Water Feature:
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746445/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746446/test_case_cascading_water_feature200.zip)
[test_case_cascading_water_feature300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746447/test_case_cascading_water_feature300.zip)
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746448/test_case_cascading_water_feature400.zip)

Viscous Net:
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746450/test_case_viscous_net65.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746451/test_case_viscous_net100.zip)
[test_case_viscous_net150.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746452/test_case_viscous_net150.zip)
[test_case_viscous_net200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746453/test_case_viscous_net200.zip)

Lighthouse:
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746454/test_case_lighthouse125.zip)
[test_case_lighthouse250.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746455/test_case_lighthouse250.zip)
[test_case_lighthouse375.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746456/test_case_lighthouse375.zip)
[test_case_lighthouse500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1746457/test_case_lighthouse500.zip)

**Comment by gimble3d** [comment]
Forgot to add an image showing CPU/GPU load while baking:
![trial_run_02_feb_18_2018](https://user-images.githubusercontent.com/36137492/36517481-684a5ac6-173f-11e8-9924-859ab7fcee48.JPG)

Neither the CPU or GPU appeared to be "over-stressed" during the bake, but the image may be useful for comparison purposes...
