### ISSUE TITLE
[Test Case Results] getrad

### ISSUE THREAD

**Issue by Getrad** [rlguy/Blender-FLIP-Fluids-Beta#55]
Hey Ryan

I attempted all 4 test case files with no success.
At a quick look, all error messages appeared the same issue.
Here's the logs for all, and one screen grab of the console message.
1st machine:
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730188/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730189/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730190/test_case_viscous_net65.zip)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730186/test_case_cascading_water_feature100.zip)

2nd (Main) machine:
![fluid_in_an_invisible_box_flip_fluid](https://user-images.githubusercontent.com/13664520/36293087-49aa88e0-129c-11e8-9b50-7021f5e79b28.PNG)
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730191/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730192/test_case_fluid_in_an_invisible_box200.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730193/test_case_lighthouse125.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730194/test_case_viscous_net100.zip)

It seems to think the addon is not for Windows, or it may be a permissions issue (which should not be the case on either test machine).
Tried uninstalling and reinstalling, re-downloading, uninstall/reinstall...still no luck.

Thanks again

**Comment by rlguy** [comment]
Hey Getrad,

There were three other users who were having the same error. They were able to resolve the problem by reinstalling their nvidea graphics drivers.

Let me know if the solution in this issue solves your problem: #6 

If this does not solve the problem, I would suspect that your GPU is too old to support the required OpenCL functionality and I could create you a build without OpenCL to try out.

**Comment by Getrad** [comment]
Thanks Ryan!
Updated and 1st test sim is running now

**Comment by Getrad** [comment]
Finally got the results from both my test workstations
Main workstation:
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733944/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733945/test_case_fluid_in_an_invisible_box100.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733946/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733947/test_case_viscous_net65.zip)

Second workstation:
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733948/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733949/test_case_fluid_in_an_invisible_box200.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733950/test_case_lighthouse125.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1733951/test_case_viscous_net65.zip)

Looks like they all worked well.

**Comment by rlguy** [comment]
Thanks Getrad!

I checked your results and it looks like the tests ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
