### ISSUE TITLE
[Test Case Results] Francois-Grassard

### ISSUE THREAD

**Issue by Francois-Grassard** [rlguy/Blender-FLIP-Fluids-Beta#56]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1730542/test_case_fluid_in_an_invisible_box100.zip)

The simulation looks good. I think everything is OK. Thanks you !

**Comment by Francois-Grassard** [comment]
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1731400/test_case_fluid_in_an_invisible_box300.zip)

Same thing, but with a grid of 300 now. The simulation looks good, too.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by Francois-Grassard** [comment]
Thank you  ! I'm going to check that right now !

And because I just finished a last test, here a my last report :)

[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732380/test_case_cascading_water_feature200.zip)

**Comment by Francois-Grassard** [comment]
![image](https://user-images.githubusercontent.com/7964475/36323188-54bd6734-1350-11e8-81e9-1a2a7424c300.png)

And ..... it works !!!! Thank you Ryan !
It's going to be fun to play with this addon.

The computing using the GPU looks pretty fast !

**Comment by Francois-Grassard** [comment]
Hello Again ! 

First report ;) When I try to show my particles in the viewport, by checking "Icosphere" and unchecking "Render Only", I have to move in the timeline from the next (or previous) frame, to force the update.

![image](https://user-images.githubusercontent.com/7964475/36323703-1a2125a0-1352-11e8-99fb-a3354ff93db8.png)

Just to let you know, I have a bunch of particles. Maybe it could be the reason :)

![image](https://user-images.githubusercontent.com/7964475/36323729-38b592b2-1352-11e8-932a-a6fcc5735e70.png)

**Comment by rlguy** [comment]
Frames must be reloaded for mesh changes to take effect at the moment. There is a feature request and more info why this is in this issue: #25

**Comment by Francois-Grassard** [comment]
Great ! Thank you for your quick feedback !

Question : can we publish photos / articles / tweets / Facebook posts about our tests with the addon or do we have to keep silent during the beta phase ? I prefer to ask before doing something wrong. :)

**Comment by rlguy** [comment]
No problem! You’re free to post whatever you want.
