### ISSUE TITLE
[Test Case Results] HEEROCKSS

### ISSUE THREAD

**Issue by HEEROCKSS** [rlguy/Blender-FLIP-Fluids-Beta#57]
[test_case_cascading_water_feature400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1732172/test_case_cascading_water_feature400.zip)
A Test with my 72 Cores Server, worked perfectly fine but it took longer than my overclocked 3930k. Seems Simulations scale better with fast single core performance than lots of cores.

**Comment by rlguy** [comment]
Hey HEEROCKSS,

You can post all of your test results in the same test case thread, even if it is on a different system. I have added your above test with some comments to your original thread: #35
