### ISSUE TITLE
Viscosity: Higher Value = More Viscous or less?

### ISSUE THREAD

**Issue by Retrific** [rlguy/Blender-FLIP-Fluids-Beta#59]
If I want the fluid to be thicker, do I increase the viscous value or lower it?
Is a value of zero = viscosity of water?
What if I want to it to be less viscous than water, I cant lower the value below zero.

**Comment by rlguy** [comment]
Hey Retrific,

Higher viscosity values relate to thicker fluids.

0 is the least amount of viscosity you can have in the simulator. When viscosity is set to 0, viscosity calculations are turned off and it is the same as having the viscosity option checked off. If it is set to anything greater than zero, the simulator will start performing viscosity calculations.

Hope this clears things up! Let me know if you have any other questions.
