### ISSUE TITLE
Domain Debug Settings

### ISSUE THREAD

**Issue by Toudou-Blender** [rlguy/Blender-FLIP-Fluids-Beta#60]
In the document of the Domain Debug Settings, I think that it had better add a text that it should change wireframe mode to display the debugging results clearly in the 3D view port.

![iamge1](https://user-images.githubusercontent.com/36343687/36329201-72876b40-13a8-11e8-8738-1213e7e0579a.jpg)
![fig2](https://user-images.githubusercontent.com/36343687/36329208-752cc962-13a8-11e8-8474-67cb85033156.jpg)

**Comment by rlguy** [comment]
Great suggestion! I have added this tip to the wiki page:

https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Debug-Settings
