### ISSUE TITLE
[Feature Request] Ability to keep simulation data after initial save

### ISSUE THREAD

**Issue by Xepher313** [rlguy/Blender-FLIP-Fluids-Beta#62]
Long story short, I simulated a thing, and then saved the project for the first time, and all the sim data got removed.

I think it would be a good feature to not have that happen, either by preventing simulations from happening if the project isn't saved, or by moving the sim data when the project is initially saved.

**Comment by rlguy** [comment]
This sounds like a bug, I’ll look into this and keep you updated in this issue.

Your simulation data should still be on your computer, probably wherever the default cache folder is. You can find this by opening a new blend and checking the cache directory setting. In your saved file, set the cache directory to where the old cache is and your simulation files should be back.

**Comment by rlguy** [comment]
This bug has been fixed and will be included in the next version of the beta addon (v0.1.2b).
