### ISSUE TITLE
[ISSUE] Spray extremely active and in some cases inaccurate?

### ISSUE THREAD

**Issue by TripleDots** [rlguy/Blender-FLIP-Fluids-Beta#65]
In nearly all of my testing the spray adds up even when nothing is happening.
The bubbles and foam particles are fine.
Even on higher resolutions this happens. But in the images I used a final res of 120.

I enlarged the particles so you can see it better.
Domain size is 1m x 1m x 1m. The fluid is 1x1x0.25m

(Don't worry about the light grey underneath the objects in the water. That's caused because they are partly out of the domain.)

![fluid30002](https://user-images.githubusercontent.com/10249053/36342788-b846ea88-1403-11e8-9925-13b8b0db880b.png)
![fluid30003](https://user-images.githubusercontent.com/10249053/36342789-b85fa2bc-1403-11e8-832d-872787210eec.png)
![fluid30004](https://user-images.githubusercontent.com/10249053/36342790-b8772306-1403-11e8-8989-fff0a2c97e83.png)
![fluid30005](https://user-images.githubusercontent.com/10249053/36342791-b891321e-1403-11e8-979a-a69c0e88e74a.png)

This happens on all my bakes. Even with the test files (cascading_water_feature specifically.)
They often spawn outside or far above the fluids as well. 
I am playing with PIC VS FLIP right now to see if it will help. Will return ASAP with my findings.

![33334](https://user-images.githubusercontent.com/10249053/36342905-685619e8-1405-11e8-9152-7c46d6f610f2.JPG)

**Comment by rlguy** [comment]
Hey TripleDots,

Thanks for letting me know about this issue. I am suspecting that this is an issue relating to users with AMD GPUs. Another tester reported a similar issue with whitewater generation who is also using the same GPU model (AMD RX480). I'll be closing this issue and moving the discussion to this issue: #78
