### ISSUE TITLE
[Test Case Results] balesandre

### ISSUE THREAD

**Issue by balesandre** [rlguy/Blender-FLIP-Fluids-Beta#66]
Hello, I ran the cascading_water_feature-lite.blend test case at 100 and 200 resolution and I think it did not work correctly. below the results

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1734369/test_case_cascading_water_feature100.zip)
[test_case_cascading_water_feature200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1734370/test_case_cascading_water_feature200.zip)

**Comment by rlguy** [comment]
Thanks balesandre!

What happened to make you think a test did not run correctly? The test results look okay to me, but you noted that the 100 resolution test did not run successfully. Can you describe any problems that happened?

**Comment by balesandre** [comment]
I'll do it again and give a printscreen. maybe I got confused!

**Comment by balesandre** [comment]
new tests everything worked. I think I had thought it was wrong because the button turned red.

test case fluid in an invisible box in 100 and 200 
test case viscous net in 65 and 100 samples

[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1735312/test_case_fluid_in_an_invisible_box200.zip)
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1735313/test_case_viscous_net65.zip)
[test_case_viscous_net100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1735314/test_case_viscous_net100.zip)
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1735315/test_case_fluid_in_an_invisible_box100.zip)

**Comment by rlguy** [comment]
Thanks for the update! Looks like the simulator is running correctly on your machine.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by balesandre** [comment]
Good Morning. new tests are attached.
I had access to the dropbox folder and installed the version "bl_flip_fluids-x64-v0.1.1b" but the attached tests are still the version of "bl_flip_fluids_test_suite-x64_v0.1.1t" (test version). Should I continue with the trial version?


[test_case_fluid_in_an_invisible_box400.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1739718/test_case_fluid_in_an_invisible_box400.zip)
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1739719/test_case_lighthouse125.zip)
[test_case_lighthouse250.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1739720/test_case_lighthouse250.zip)
[test_case_fluid_in_an_invisible_box300.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1739721/test_case_fluid_in_an_invisible_box300.zip)

**Comment by rlguy** [comment]
Hey balesandre,

Thanks for the test results, they look like they ran okay!

You're free to use the **bl_flip_fluids-x64-v0.1.1b** (Full Beta Version) to experiment with the addon however you want.

The **bl_flip_fluids_test_suite-x64_v0.1.1t** (Test Suite Version) is only for submitting test results.

**Comment by balesandre** [comment]
follow some more tests. Only test_case_lighthouse500 is missing.

I was wondering if there is interest in the information of the cash files because they are already 150gbytes.


[test_case_viscous_net150.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1748191/test_case_viscous_net150.zip)
[test_case_viscous_net200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1748192/test_case_viscous_net200.zip)
[test_case_lighthouse375.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1748193/test_case_lighthouse375.zip)

**Comment by rlguy** [comment]
Thanks for taking all the time to run these test cases! You may delete the cache files when you no longer need them. All the data we need are contained in the exported test case results.

**Comment by balesandre** [comment]
uhull.


[test_case_lighthouse500.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1754783/test_case_lighthouse500.zip)
