### ISSUE TITLE
[Test Case Results] SageKri

### ISSUE THREAD

**Issue by SageKri** [rlguy/Blender-FLIP-Fluids-Beta#67]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1734426/test_case_cascading_water_feature100.zip)
[test_case_fluid_in_an_invisible_box200.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1734427/test_case_fluid_in_an_invisible_box200.zip)
I ran these two test scenes, was quite surprised at the Flip solver times for both of these and quite enjoyed this experience.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors. Great to hear you're enjoying the simulator!

You Dropbox folder contains a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
