### ISSUE TITLE
[Feature Request] Allow user to select which GPU to use

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids-Beta#7]
**Problem**

The simulator doesn't have a 'smart' method of selecting which GPU to use, it just picks the first GPU from a list. This can cause the simulator to choose the less powerful GPU, or even an integrated graphics chip which will slow down simulation baking.

**Solution**

1. Add an interface element to the _Addon Preferences_ menu that allows the user to select which GPU they want the simulator to use.
2. Use a smarter method to try and detect the more powerful GPU and use that as the default selection

**Workaround**
_Note: This workaround only applies to the FLIP Fluids Beta addon, not the Test Suite addon_

If the addon is selecting the wrong GPU, try disabling GPU features until this issue is fixed. Simulations may run faster using your CPU.

![disable_gpu_features](https://user-images.githubusercontent.com/4285191/36189959-33e878e8-110a-11e8-9780-2aa942eaa07d.jpg)

**Comment by RevDr** [comment]
Just running my first test - sure this is a daft question - but where are the GPU options?

**Comment by rlguy** [comment]
Not a bad question! The GPU options are only available in the full beta addon, not the test suite addon. I have updated the workaround noting this.

**Comment by RevDr** [comment]
Should my GPU be doing anything on the test version?  Currently running a 300 resolution test and noticed although my CPU is working my GPU utilization is running at 1% or 2% most of the time (CPUID HW Monitor)

**Comment by rlguy** [comment]
Low GPU usage is normal.

The simulator offloads some calculations to the GPU to boost performance. Many FLIP calculations aren't perfectly suited for GPU processing, so the full power of the GPU cannot be 100% utilized. Often the GPU usage is under 5%, but with this low percentage, the calculations can still run much faster on the GPU than CPU. For example, mesh data is generated on the GPU and in tests, when running on CPU, these calculations could be two to five times slower. 

The performance boost will depend on your hardware. In the full version, you can try disabling the GPU features to test if the calculations run faster on your CPU.

**Comment by RevDr** [comment]
OK - thanks - makes sense.

**Comment by rlguy** [comment]
> Solution 2: Use a smarter method to try and detect the more powerful GPU and use that as the default selection

The next version (Test Suite **v0.1.2t** and Beta **v0.1.2b**) will include this improvement.

Functionality to specify which GPU to use is still in progress.

**Comment by rlguy** [comment]
An option has been added to the addon preferences to select which GPU to use as a compute device. If no device is selected, the addon will automatically try to select the most 'powerful' device. Tip: remember to save your user settings so that Blender remembers your GPU selection preference.

This feature will be included in the next beta version (**0.1.3b**).

![gpu_selection](https://user-images.githubusercontent.com/4285191/36765536-8c43b840-1be6-11e8-84dc-9cd72e3ede3c.jpg)
