### ISSUE TITLE
[Test Case Results] MobyMotion

### ISSUE THREAD

**Issue by MobyMotion** [rlguy/Blender-FLIP-Fluids-Beta#70]
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1736343/test_case_lighthouse125.zip)

This seems to have run without any problems. 

However, initially I had an issue where the simulation would stop after a few frames and give me an access denied error, which I have attached a screenshot of here. The test scene file and the test suite were in dropbox. I fixed it by moving the scene file to a local only folder, keeping the test suite in dropbox. This did the trick

<img width="1126" alt="screen shot 2018-02-19 at 09 35 58" src="https://user-images.githubusercontent.com/29977055/36373646-9f964cd2-1560-11e8-9363-635b6de0226f.png">

**Comment by rlguy** [comment]
Thanks MobyMotion!

I checked your results and it looks like the test ran without errors. Thanks for letting me know about the Dropbox error. There was another user who was having the same problem. I've opened an issue to add documentation about this error here: #75.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
