### ISSUE TITLE
[test case results] cansoftinc

### ISSUE THREAD

**Issue by cansoftinc** [rlguy/Blender-FLIP-Fluids-Beta#71]
Hi, the below test case results (test_case_fluid_in_an_invisible_box100) seemed to have run without errors.
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1736366/test_case_fluid_in_an_invisible_box100.zip)

**Comment by cansoftinc** [comment]
Hi, the above test case results (test_case_fluid_in_an_invisible_box100) seemed to have run without errors.

**Comment by rlguy** [comment]
Hey cansoftinc,

You may post all of your test case results to the same issue. I have added your above results to your other thread: #72
