### ISSUE TITLE
[Test Case Results] cansoftinc

### ISSUE THREAD

**Issue by cansoftinc** [rlguy/Blender-FLIP-Fluids-Beta#72]
Hi, the below results seemed to have run without errors.

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1736370/test_case_cascading_water_feature100.zip)

**Comment by cansoftinc** [comment]
Hi,  the above results seemed to have run without errors.

**Comment by cansoftinc** [comment]
Below are the results for test_case_lighthouse125, I didn't capture the error cause the machine hanged, consequently I had to cold boot.
[test_case_lighthouse125.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1737358/test_case_lighthouse125.zip)

**Comment by rlguy** [comment]
> cansoftinc:
>
> Hi, the below test case results (test_case_fluid_in_an_invisible_box100) seemed to have run without errors.
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1736366/test_case_fluid_in_an_invisible_box100.zip)

Thanks cansoftinc!

I checked your results, and aside from the lighthouse scene, it looks like the tests ran without errors. Please let me know if your machine continues to hang while simulating or if you run into any other errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
