### ISSUE TITLE
[Test Case Results] Sprunth

### ISSUE THREAD

**Issue by Sprunth** [rlguy/Blender-FLIP-Fluids-Beta#8]
[test_case_fluid_in_an_invisible_box100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723076/test_case_fluid_in_an_invisible_box100.zip)

I was using my PC for some other tasks while this ran so the timing/performance may be impacted.

**Comment by rlguy** [comment]
Thanks Sprunth!

I checked your results and it looks like the test ran without errors.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
