### ISSUE TITLE
(Test Case Results )emihich

### ISSUE THREAD

**Issue by emihich** [rlguy/Blender-FLIP-Fluids-Beta#83]
I ran the test in high resolution 375
it took a long time to bake , about 12 hours 
but it seems that I've completed it without errors.

[test_case_lighthouse375.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1738994/test_case_lighthouse375.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors. By the way, I checked your times and the simulation took a total of 10h42 minutes. 9h54m were spent simulating and 48 minutes were spent writing the mesh files to disk. I was wondering if you are storing the cache files on a hard-disk drive or a solid-state drive? Perhaps there are some improvements to be made in how the addon saves mesh files.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by emihich** [comment]
Dear Ryan
  I have a brand new HP Viper computer
That I've used to run the test.
    The boot drive is a SSD disk
, but with only 256 gig and I've chosen to use
The non SSD internal disk to
Have the directory for the files created by
The test .
  Hope this clarifies it
I can run a new similar test using the Root
OS main disk for comparison if needed
   Thank you for sending me the New file

          Luiz Eduardo Mihich
