### ISSUE TITLE
How to specify the amount of bubbles vs. foam etc?

### ISSUE THREAD

**Issue by Retrific** [rlguy/Blender-FLIP-Fluids-Beta#84]
My simulation creates a lot of foam and spray but little bubbles, however I think it could need way more bubbles. But when I increase the various settings for whitewater generation the amount of foam and spray increases too but I only want more bubbles.
What do I have to do?

**Comment by rlguy** [comment]
Hey Retrific!

If you attach your scene I may be able to troubleshoot your settings more accurately. You will need to compress your .blend to a zip to attach the file.

Here are some general guildlines for increasing amount of bubbles:

1. **Increase the _Turbulence Emission Rate_** - bubbles are created in areas of high turbulence. Increasing this value should generate more bubbles in turbulent areas.

2. **Lower the _Min/Max Tubulence_ threshold values** - Bubbles will start emitting when the local turbulence is above the min turbulence value. Try decreasing the range to trigger bubble emission in areas of lower turbulence. Ex: min 25, max 125.

3. **Set a realistic range for _Min/Max Energy Speed_** - higher energy fluid will produce more particles. These values control the speed range (in m/s) where particles are generated. Depending on the scale of your simulation, the default values may not be realistic. If you have a smaller scene, the fluid speed will likely be slower so try lower this range. Ex: Min 0.2, Max 3.0.

Let me know if any of these tips work or if you have more questions! Again, if you are able to send me the scene I’ll be able to look at your settings and have a better idea of what could be done to improve your scene.
