### ISSUE TITLE
[Hardware issue] (AMD) CPU baking crash

### ISSUE THREAD

**Issue by TripleDots** [rlguy/Blender-FLIP-Fluids-Beta#86]
So I went in to try the CPU solver as the RX480 seems to be bugged (see: https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/78 ).
But for whatever reason, baking rarely goes beyond the 16th and 17th frame on all of my renders when the resolution is specifically above 200 with the CPU. EDIT: the higher the resolution, the faster it crashes.)
It happens almost every 

time with white water enabled and it crashes less without white water. But still around that 17 frame mark.
There is no error message or crash log created when this happens.

There is no overheating happening.
Limiting cores doesn't do anything either.
RAM is not even near full use.
Disks are empty as well.

AMD Bulldozer 8350 x8 BLACK EDITION (stock)
24gb DDR3 ram 1600mhz
RX480 (stock)
Windows 10

*This also occurs on my AMD Phenom II x4 840 and x6 which makes me believe that it's another AMD focused issue. So if there are more folks that can test this:

Turn white water on (white water, bubbles and spray)
Set RES to 200
Turn off: GPU Scalar Field and GPU Particle Advection
Turn on: Enable Adaptive Time Stepping for obstacles

Blend file:
https://we.tl/tw8ksLYPiO

[flip_fluid_stats.pdf](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1741935/flip_fluid_stats.pdf)

**Comment by rlguy** [comment]
I tested this and I also get the error. I'm running on Intel CPU and NVidia GPU, so this bug is not limited to AMD hardware. From the Blender system console:

![tripledots_scene_error](https://user-images.githubusercontent.com/4285191/36451264-52b84556-1645-11e8-8fe8-2c0370b76f61.jpg)

The error means that the simulator is trying to access memory that is out of bounds. This shouldn't be too difficult to debug. I'm taking a further look into this now and I'll keep you updated in this thread.

**Comment by rlguy** [comment]
Thanks for finding and reporting this! This bug occurs when the _GPU Scalar Field_ option is turned off. Your scene provided the perfect setup for triggering this error.

This bug has been fixed and and will be included in the next version (**0.1.2b**).

### Workaround

Until the next version, keep the _GPU Scalar Field_ option turned on. As far as I know, this GPU feature does not affect AMD users. If this option does cause problems, please let me know.

**Comment by TripleDots** [comment]
Thank you! The current work around works.
It does seem that the white water particles are still a bit more playful (but still very close to CPU only.) But that is from one tiny test.
I will fully test this tomorrow.
