### ISSUE TITLE
[Test Case Results] OrangeGloves

### ISSUE THREAD

**Issue by orangegloves** [rlguy/Blender-FLIP-Fluids-Beta#88]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1742794/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

> comment: I did it at 200, and thought it didn't finsih because it said resume, but then when I did it at 100, I realized that it had finished it just says that

Yes, it is meant to say 'resume' at the end. In the beta version there is a way to continue/resume baking more frames.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
