### ISSUE TITLE
[Test Case Results] TripleDots

### ISSUE THREAD

**Issue by TripleDots** [rlguy/Blender-FLIP-Fluids-Beta#9]
This is at 100. I am going to bake 200 through the night as I have some work to do.
Minus a few particles going through the object (which compared to the build in fluid means that this one beta is already flawless ha!) Everything went well.
I played back with 8fps even while baking to see if I could and it worked well.

[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1723665/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks TripleDots!

I checked your results and it looks like the test ran okay, but you are affected by issue #7.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.

**Comment by TripleDots** [comment]
What does it mean when it selects the wrong GPU? My CPU doesn't have a GPU. 
Also thanks for the updated build!

**Comment by rlguy** [comment]
Sorry, you are correct! I'm unfamiliar with AMD hardware and it turns out I was reading the test case wrong. Everything is working correctly for you.
