### ISSUE TITLE
Blender crashing while trying to change roughness of white material and  rendering it 

### ISSUE THREAD

**Issue by emihich** [rlguy/Blender-FLIP-Fluids-Beta#92]
Everytime that I've increased the roughness in the default Water material spinner 
 and tried to render with Cycles , Blender crashed 
3 times in a row
Rendering in Full HD resolution without tweaking the water material , worked fine, and no crashes .
Not a memory issue , I have 32 gig ram
Maybe , it is a bug,

**Comment by rlguy** [comment]
Hey, this sounds very odd! I have some questions about this:

1. Does the crash still happen now? After rebooting your system?
2. How large is the mesh (number of verts/triangles)
3. When does the crash occur and is it the same everytime:
    - Right before rendering (right after pressing render/animation button)?
    - While initializing the render (initializing objects, building BVH)?
    - In the middle of rendering?
    - Right after rendering completes?

This being related to the roughness of the material sounds very weird and makes me think that this could be an issue in Cycles. I also wonder if this could be related to issue #34

**Comment by emihich** [comment]
Dear Ryan
  I think that I nade a mistake and
Maybe I associated the roughneds of the material , but real reason could be
that
I thought, I would be rendering CPU
but was using GPU instead
And I hadn't configured before
In the preferences
My NVidia GTX 770 ti
  Gotta be that the real problem
Renders are better and not crashing
Animore !

**Comment by rlguy** [comment]
Alright, great to hear that it’s now working!

**Comment by emihich** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "imprensasecult@gmail.com: MOVIMENTO
CASA DAS ONZE JANELAS" e queria saber se você pode ajudar assinando também.

A nossa meta é conseguir 2.500 assinaturas e precisamos de mais apoio. Você
pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/ZWW9j2LRF5

Obrigado!
Luiz Eduardo
