### ISSUE TITLE
[Test Case Results] Gerkinfeltser

### ISSUE THREAD

**Issue by Gerkinfeltser** [rlguy/Blender-FLIP-Fluids-Beta#93]
No problems running res 100 test case here (I think).
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1748168/test_case_cascading_water_feature100.zip)

**Comment by rlguy** [comment]
Thanks Gerkinfeltser!

I checked your results and it looks like the test ran okay, but you are affected by issue #7. This issue has been fixed and the new 'Test Suite' version should be available now.

This issue does not break the simulator, so you will still be able to receive and test builds. I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
