### ISSUE TITLE
[Test Case Results] Mitsuma

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids-Beta#95]
[test_case_cascading_water_feature100.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749066/test_case_cascading_water_feature100.zip)

Test seemed to run fine and successful, only thing I noticed is that it was only using about 55-65% of my CPU. 
![taskmgr_2018-02-22_19-14-21](https://user-images.githubusercontent.com/8568089/36556404-5bab4e44-1805-11e8-9714-c04541f2a0ac.png)
Not sure if intended, thought I might ask. Higher Resolution does seem to have a higher impact, 200 shows higher spikes.
Small edit: I think that 2nd core usage spike was another program, not actually FLIP Fluid.

Edit: 
[test_case_viscous_net65.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1749169/test_case_viscous_net65.zip)
Added a 2nd test, showed similar CPU usage, 60% average.

**Comment by rlguy** [comment]
Thanks!

I checked your results and it looks like the test ran without errors.

Less than 100% CPU usage is normal. Here's an explanation:

> Lower than 100% CPU usage is normal. This is because fluid simulation is very memory heavy problem and memory access is slow compared to how fast your CPU is. In the simulator, there are many threads accessing large amounts of memory at the same time. The CPU must wait for memory to be fetched from RAM/Cache and this is what commonly causes decreased CPU usage. Another reason is that some calculations in the simulator are not able to be multithreaded efficiently, so these sections of calculations create a bottleneck which lowers average CPU usage.

I have updated your Dropbox folder with a build of the addon for testing. Your beta invite email should contain a link and a password to your Dropbox folder.

I will be closing this issue. Please post any further test case results to this thread.
