### ISSUE TITLE
[Feature Request] White water enhancement

### ISSUE THREAD

**Issue by guitartom47** [rlguy/Blender-FLIP-Fluids-Beta#97]
Would it be possible to have the white water simulation pick from a group of particle objects instead just a single object? It would be nice to have different shapes to the spray or foam or bubbles. Also, it would be nice to be able to randomize the size of these objects a little as they seem too uniform to me. It seems to me that the mission is to get the grid resolution to a high enough point and the white water particles varied enough that they begin to blend together. 

Off subject, here's an image that I've created - playing around.
![sploosh](https://user-images.githubusercontent.com/5819717/36557939-3a451e96-17cf-11e8-9566-1bb86c5981ee.png)

**Comment by rlguy** [comment]
Cool render!

Unfortunately this is quite difficult at the moment. The particles are rendered through instancing and uses the [dupliverts](https://docs.blender.org/manual/en/dev/editors/3dview/object/properties/duplication/dupliverts.html) Blender feature to duplicate the particles quickly. This is efficient for rendering when there are millions of particles, but it does not allow for particles of different sizes or shapes.

To add this feature would require too much restructuring of the code and I do not want to make changes this large before release. Perhaps in the future this could be implemented. This would be a great feature and I'll keep it in mind. I may reopen this feature request at a later date when I can think of a better/simpler solution to this problem.
